/**
 * Flow Testing - Default Config
 *
 * Your base configuration for flow state testing.
 */

import type { QuestionCommandMenuV4Config } from '../question-command-menu-v4/types'

export const FLOW_DEFAULT_CONFIG: QuestionCommandMenuV4Config = {
  animation: {
    duration: 350,
    collapseDuration: 150,
    contentFadeDuration: 0,
    contentFadeDelay: 0,
    backdropMode: 'size',
    backdropDelay: 0,
    backdropDurationOffset: 0,
    animateSlotContainers: true,
    slotContainerDelay: 0,
    slotContainerDurationOffset: 100,
  },
  layout: {
    triggerWidth: 360,
    triggerHeight: 44,
    panelWidth: 480,
    fillWidth: false,
    borderRadius: 20,
    topGap: 16,
    bottomGap: 16,
    backdropTopOffset: 0,
  },
  appearance: {
    borderRadius: '2xl',
    shadow: '2xl',
    shine: 'shine-2-subtle',
    background: 'tertiary',
    gradient: 'subtle-depth-md',
    gradientColor: 'tertiary',
    squircle: true,
  },
  trigger: {
    defaultMode: 'input',
    paddingLeft: 12,
    paddingRight: 12,
    paddingTop: 0,
    paddingBottom: 0,
    paddingExpandedLeft: 0,
    paddingExpandedRight: -4,
    showSearchIcon: false,
    showKeyboardHint: false,
    keyboardHintText: '/',
    cursor: 'text',
    buttons: [
      // Send button - shows when typing, triggers submit (disabled by default, flow config controls visibility)
      {
        id: 'send',
        position: 'right',
        enabled: false,
        type: 'icon',
        variant: 'primary',
        size: 'sm',
        roundness: 'squircle',
        icon: 'send',
        showWhen: 'has-value',
        action: 'submit',
      },
      // Add button - xs text only (same style as Edit, disabled by default, enabled in adding state)
      {
        id: 'add-button',
        position: 'right',
        enabled: false,
        type: 'text',
        variant: 'primary',
        size: 'xs',
        roundness: 'squircle',
        label: 'Add',
        showWhen: 'expanded',
        action: 'submit',
      },
      // Edit button - xs text only (disabled by default, enabled in response/editing)
      {
        id: 'edit-small',
        position: 'right',
        enabled: false,
        type: 'text',
        variant: 'tertiary',
        size: 'xs',
        roundness: 'squircle',
        icon: 'delete',
        showWhen: 'expanded',
        label: 'Edit',
      },
      // Plus indicator when collapsed (for idle/adding states)
      {
        id: 'plus-collapsed',
        position: 'right',
        enabled: true,
        type: 'indicator',
        variant: 'tertiary',
        size: 'sm',
        icon: 'add',
        showWhen: 'collapsed',
      },
      // Arrow indicator when collapsed (for response/editing states)
      {
        id: 'arrow-collapsed',
        position: 'right',
        enabled: false,
        type: 'indicator',
        variant: 'tertiary',
        size: 'sm',
        icon: 'arrow-right',
        showWhen: 'collapsed',
      },
      // Delete button - icon only (disabled by default, enabled in response/editing)
      {
        id: 'delete-expanded',
        position: 'right',
        enabled: false,
        type: 'icon',
        variant: 'tertiary',
        size: 'sm',
        roundness: 'squircle',
        icon: 'delete',
        showWhen: 'expanded',
      },
    ],
  },
  triggerDisplay: {
    placeholderText: 'Add a question...',
    addPlaceholderText: 'Add a question...',
    savedValueColor: 'primary',
    showEditIndicator: true,
  },
  slots: {
    top: {
      enabled: true,
      heightMode: 'auto',
      fixedHeight: 48,
      maxHeight: 480,
      minHeight: 0,
      appearance: {
        background: 'secondary',
        shine: 'none',
        borderRadius: 14,
        inset: 4,
        borderWidth: 1,
        borderColor: 'primary',
      },
      animation: {
        delayOffset: 0,
        durationOffset: -100,
        expandOrigin: 'bottom',
      },
      scroll: {
        overflowGradient: true,
        gradientHeight: 24,
        paddingTop: 8,
        paddingBottom: 8,
      },
    },
    bottom: {
      enabled: true,
      heightMode: 'auto',
      fixedHeight: 48,
      maxHeight: 100,
      minHeight: 0,
      appearance: {
        background: 'none',
        shine: 'none',
        borderRadius: 0,
        inset: 0,
        borderWidth: 0,
        borderColor: 'tertiary',
      },
      animation: {
        delayOffset: 0,
        durationOffset: 100,
        expandOrigin: 'top',
      },
      scroll: {
        overflowGradient: false,
        gradientHeight: 24,
        paddingTop: 0,
        paddingBottom: 0,
      },
    },
  },
  content: [
    { id: 'top-chat', type: 'chat', slot: 'top' },
    { id: 'bottom-buttons', type: 'buttons', slot: 'bottom' },
  ],
  contentConfigs: {
    questions: {
      item: {
        height: 56,
        gap: 4,
        paddingX: 12,
        paddingY: 8,
        borderRadius: 12,
        highlightBackground: 'quaternary',
        hoverBackground: 'tertiary',
        iconSize: 18,
        iconGap: 10,
        iconOpacity: 60,
      },
      emptyMessage: 'No questions yet. Start typing to add one.',
    },
    buttons: {
      // Base buttons - flow configs override labels/enabled state
      buttons: [
        {
          id: 'btn1',
          label: 'Improve answer',
          icon: 'none',
          variant: 'shine',
          enabled: true,
        },
        {
          id: 'btn2',
          label: 'Update',
          icon: 'none',
          variant: 'secondary',
          enabled: false,
        },
        {
          id: 'btn3',
          label: 'Regenerate',
          icon: 'sparkle',
          variant: 'tertiary',
          enabled: false,
        },
        {
          id: 'btn4',
          label: 'Cancel',
          icon: 'close',
          variant: 'tertiary',
          enabled: false,
        },
      ],
      direction: 'horizontal',
      gap: 8,
      size: 'md',
      paddingLeft: 4,
      paddingRight: 4,
      paddingTop: 0,
      paddingBottom: 4,
    },
    filters: {
      options: [
        { id: 'all', label: 'All', count: 12 },
        { id: 'pending', label: 'Pending', count: 3 },
        { id: 'approved', label: 'Approved', count: 7 },
        { id: 'flagged', label: 'Flagged', count: 2 },
      ],
      defaultValue: 'all',
    },
    tabs: {
      options: [
        { id: 'recent', label: 'Recent' },
        { id: 'starred', label: 'Starred' },
        { id: 'all', label: 'All' },
      ],
      defaultValue: 'all',
    },
    chat: {
      message: {
        paddingX: 12,
        paddingY: 10,
        gap: 12,
        borderRadius: 24,
        maxWidth: 85,
        squircle: true,
      },
      container: {
        paddingTop: 16,
        paddingBottom: 16,
      },
      userMessage: {
        background: 'quaternary',
        textColor: 'primary',
        shine: 'none',
      },
      assistantMessage: {
        background: 'secondary',
        textColor: 'primary',
        shine: 'none',
      },
      responseActions: {
        enabled: true,
        actions: [
          { id: 'copy', enabled: true },
          { id: 'regenerate', enabled: true },
          { id: 'speak', enabled: true },
        ],
      },
      showTypingIndicator: false,
      emptyMessage: 'Ask a question to see the AI response here',
    },
    suggestions: {
      maxWords: 15,
      showSearch: true,
      item: {
        height: 48,
        gap: 4,
        paddingX: 12,
        paddingY: 8,
        borderRadius: 12,
        highlightBackground: 'quaternary',
        hoverBackground: 'tertiary',
        showConfidence: true,
      },
      emptyMessage: 'No suggestions available',
    },
  },
  placeholder: 'Add a question',
  defaultMode: 'input',
  debug: false,
}
