/**
 * Pricing Modal Presets
 *
 * Default configuration and preset variations.
 */

import type { PricingPlaygroundConfig, PricingPresetMeta } from './types'

// ============================================================================
// Default Configuration
// ============================================================================

export const DEFAULT_PRICING_CONFIG: PricingPlaygroundConfig = {
  container: {
    width: 380,
    height: 480,
    padding: 24,
    gap: 24,
    borderRadius: 16,
    cornerShape: 'round',
    background: 'secondary_p1',
    shine: 'shine-3',
    depth: 'depth-gradient-2',
    shadow: '2xl',
    borderWidth: 0,
    borderColor: 'border-primary',
  },
  radialFlare: {
    enabled: false,
    flare1: {
      enabled: false,
      color: 'gray-400',
      opacity: 16,
      size: 220,
      blur: 30,
      offsetX: 90,
      offsetY: -70,
    },
    flare2: {
      enabled: true,
      color: 'blue-500',
      opacity: 30,
      size: 120,
      blur: 60,
      offsetX: 50,
      offsetY: -65,
    },
    flare3: {
      enabled: true,
      color: 'gray-200',
      opacity: 9,
      size: 260,
      blur: 25,
      offsetX: 20,
      offsetY: -75,
    },
  },
  decorations: {
    noise: {
      enabled: true,
      opacity: 25,
      scale: 1,
      radialFade: 85,
      blendMode: 'multiply',
    },
    sparkles: {
      enabled: false,
      count: 7,
      size: 10,
      sizeVariation: 50,
      opacity: 45,
      radialFade: 50,
      color: 'white',
      spread: 120,
    },
    rings: {
      enabled: false,
      count: 3,
      startRadius: 100,
      gap: 35,
      strokeWidth: 1.5,
      opacity: 40,
      radialFade: 50,
      color: 'gray-400',
      arcAngle: 105,
    },
  },
  asset: {
    show: true,
    height: 40,
    background: 'none',
    xOffset: -6,
    coinStack: {
      enabled: true,
      presetId: 'default',
      width: 50,
      alignment: 'left',
      showBackground: false,
      background: 'tertiary',
      backgroundRadius: 16,
      cornerShape: 'round',
      sizeMode: 'fixed',
      backgroundPadding: 8,
      fixedSize: 56,
      shine: 'shine-3',
      depth: 'subtle-depth-30-primary',
      shadow: 'lg',
    },
  },
  closeButton: {
    show: true,
    position: 'top-right',
    offset: 16,
    size: 'md',
    iconStrokeWidth: 2.5,
    iconColor: 'text-quaternary',
    backgroundMode: 'always',
    backgroundColor: 'bg-quaternary',
    backgroundOpacity: 50,
    backgroundRadius: 'full',
  },
  header: {
    title: 'Upgrade to Pro',
    titleColor: 'text-primary',
    titleSize: '2xl',
    titleWeight: '600',
    textAlign: 'left',
    showSubheader: true,
    subheader: 'Unlock premium features and higher limits',
    subheaderColor: 'text-quaternary',
    subheaderSize: 'sm',
    subheaderWeight: '400',
    gap: 4,
    topOffset: -18,
  },
  separator: {
    show: false,
    position: 'after-content-b',
    thickness: 1,
    color: 'border-secondary',
    fullWidth: true,
    insetAmount: 0,
  },
  contentA: {
    show: true,
    type: 'wireframe',
    height: 48,
    lineCount: 3,
    lineGap: 8,
    textColor: 'text-secondary',
    textSize: 'sm',
    textWeight: '400',
  },
  contentB: {
    show: true,
    type: 'wireframe',
    height: 0,
    lineCount: 4,
    lineGap: 8,
    textColor: 'text-tertiary',
    textSize: 'xs',
    textWeight: '400',
    fill: true,
    checklistLayout: {
      maxWidth: 0,
      centered: false,
      noWrap: false,
      overflow: false,
    },
  },
  button: {
    label: 'Upgrade',
    variant: 'primary',
    size: 'md',
    cornerSquircle: true,
  },
  proCard: {
    title: 'Pro',
    multiplier: 2,
    gradient: 'arcade-blue',
    text: {
      fontSize: 36,
      fontWeight: '700',
      letterSpacing: -0.02,
      titleGradient: 'text-primary',
      multiplierGradient: 'ocean-depth',
    },
    container: {
      background: 'secondary',
      shine: 'shine-1-subtle',
      borderRadius: 12,
      padding: 16,
    },
    glow: {
      enabled: true,
      color: 'blue-500',
      blur: 24,
      opacity: 40,
      hideOnMobile: false,
    },
  },
  checklist: {
    items: [
      { id: 'item-1', text: 'Renews March 20', date: '{price}', icon: 'checkmark' },
      { id: 'item-2', text: 'Credits roll over', icon: 'checkmark' },
      { id: 'item-3', text: 'Downgrade anytime', icon: 'checkmark' },
    ],
    itemGap: 'tight',
    textStyle: {
      size: 'sm',
      weight: 'medium',
      color: 'tertiary',
      opacity: 100,
    },
    iconStyle: {
      size: 'base',
      weight: 'duotone',
      color: 'tertiary',
      opacity: 80,
    },
    dateStyle: {
      size: 'sm',
      weight: 'normal',
      color: 'tertiary',
      opacity: 60,
    },
  },
  animation: {
    preset: 'scale-fade',
    duration: 150,
    bounce: 0,
  },
  demo: {
    pageBackground: 'primary',
    autoOpen: false,
    showOutlines: false,
  },
  backdrop: {
    opacity: 15,
    blur: 4,
    color: 'white',
    dismissable: true,
  },
  flows: {
    'flow-a': {
      headerTitle: 'Out of credits',
      headerSubheader: 'Upgrade to continue creating.',
      contentA: {
        show: true,
        type: 'pricing-select',
        height: 88,
        lineCount: 3,
      },
      contentB: {
        show: true,
        type: 'checklist',
        height: 0,
        lineCount: 4,
      },
      buttonLabel: 'Upgrade',
      asset: { showCoinStack: true },
      contentAHeader: {
        show: true,
        text: 'Upgrade fee',
        size: 'sm',
        weight: '500',
        color: 'text-quaternary',
        opacity: 40,
      },
    },
    'flow-b': {
      headerTitle: 'Ready to upgrade?',
      headerSubheader: 'Confirm to add {additionalCredits} credits.',
      contentA: {
        show: true,
        type: 'pricing-select',
        height: 120,
        lineCount: 3,
      },
      contentB: {
        show: true,
        type: 'checklist',
        height: 0,
        lineCount: 3,
      },
      buttonLabel: "Let's create",
      asset: { showCoinStack: true },
      checklistItems: [
        { id: 'item-1', text: '{planName} renews March 20', icon: 'checkmark' },
        { id: 'item-2', text: '{credits} credits per month', icon: 'checkmark' },
        { id: 'item-3', text: 'Credits roll over', icon: 'checkmark' },
      ],
    },
    'flow-c': {
      headerTitle: "You're back",
      headerSubheader: '{credits} credits ready. Keep creating.',
      contentA: {
        show: false,
        type: 'wireframe',
        height: 48,
        lineCount: 3,
      },
      contentB: {
        show: true,
        type: 'pro-card',
        height: 0,
        lineCount: 2,
      },
      buttonLabel: 'Continue',
      asset: { showCoinStack: true, coinStackPresetId: 'arcade-blue-solid' },
    },
  },
  pricingSelect: {
    appearance: {
      background: 'tertiary',
      shine: 'shine-2',
      shadow: '2xl',
      borderRadius: 'xl',
      squircle: false,
      gradient: 'subtle-depth-md',
      gradientColor: 'tertiary',
    },
    animation: {
      duration: 425,
      collapseDuration: 250,
      easing: 'expo-out',
    },
    bottomSlot: {
      background: 'primary',
      shine: 'none',
      borderRadius: 12,
      inset: 4,
      borderWidth: 1,
      borderColor: 'primary',
    },
    triggerHoverBackground: 'quaternary',
  },
} as PricingPlaygroundConfig

// ============================================================================
// Presets
// ============================================================================

export const PRICING_PRESETS: PricingPresetMeta[] = [
  {
    id: 'default',
    name: 'Default',
    description: 'Standard pricing modal layout',
    data: DEFAULT_PRICING_CONFIG,
  },
  {
    id: 'compact',
    name: 'Compact',
    description: 'Smaller modal with tighter spacing',
    data: {
      ...DEFAULT_PRICING_CONFIG,
      container: {
        ...DEFAULT_PRICING_CONFIG.container,
        width: 360,
        height: 400,
        padding: 20,
        gap: 12,
      },
      pricingSelect: {
        ...DEFAULT_PRICING_CONFIG.pricingSelect,
        appearance: {
          ...DEFAULT_PRICING_CONFIG.pricingSelect.appearance,
          borderRadius: 'lg',
        },
        animation: { ...DEFAULT_PRICING_CONFIG.pricingSelect.animation },
        bottomSlot: { ...DEFAULT_PRICING_CONFIG.pricingSelect.bottomSlot },
      },
    },
  },
  {
    id: 'spacious',
    name: 'Spacious',
    description: 'Larger modal with generous spacing',
    data: {
      ...DEFAULT_PRICING_CONFIG,
      container: {
        ...DEFAULT_PRICING_CONFIG.container,
        width: 440,
        height: 560,
        padding: 32,
        gap: 20,
        borderRadius: 20,
      },
      pricingSelect: {
        ...DEFAULT_PRICING_CONFIG.pricingSelect,
        appearance: {
          ...DEFAULT_PRICING_CONFIG.pricingSelect.appearance,
          borderRadius: '2xl',
        },
        animation: { ...DEFAULT_PRICING_CONFIG.pricingSelect.animation },
        bottomSlot: { ...DEFAULT_PRICING_CONFIG.pricingSelect.bottomSlot },
      },
    },
  },
  {
    id: 'flare-subtle',
    name: 'Subtle Flare',
    description: 'Modal with subtle neutral radial flare',
    data: {
      ...DEFAULT_PRICING_CONFIG,
      radialFlare: {
        ...DEFAULT_PRICING_CONFIG.radialFlare,
        enabled: true,
        flare1: {
          ...DEFAULT_PRICING_CONFIG.radialFlare.flare1,
          enabled: true,
          color: 'gray-300',
          opacity: 20,
          size: 220,
          blur: 70,
          offsetX: 50,
          offsetY: -30,
        },
        flare2: {
          ...DEFAULT_PRICING_CONFIG.radialFlare.flare2,
          enabled: true,
          color: 'white',
          opacity: 15,
          size: 140,
          blur: 50,
          offsetX: 30,
          offsetY: 20,
        },
        flare3: {
          ...DEFAULT_PRICING_CONFIG.radialFlare.flare3,
          enabled: false,
          color: 'sky-400',
          opacity: 8,
          size: 80,
          blur: 30,
          offsetX: 60,
          offsetY: 40,
        },
      },
    },
  },
  {
    id: 'flare-brand',
    name: 'Brand Flare',
    description: 'Modal with brand blue accent flare',
    data: {
      ...DEFAULT_PRICING_CONFIG,
      radialFlare: {
        ...DEFAULT_PRICING_CONFIG.radialFlare,
        enabled: true,
        flare1: {
          ...DEFAULT_PRICING_CONFIG.radialFlare.flare1,
          enabled: true,
          color: 'gray-200',
          opacity: 15,
          size: 180,
          blur: 60,
          offsetX: 60,
          offsetY: -20,
        },
        flare2: {
          ...DEFAULT_PRICING_CONFIG.radialFlare.flare2,
          enabled: true,
          color: 'blue-500',
          opacity: 12,
          size: 160,
          blur: 50,
          offsetX: 20,
          offsetY: 10,
        },
        flare3: {
          ...DEFAULT_PRICING_CONFIG.radialFlare.flare3,
          enabled: true,
          color: 'sky-400',
          opacity: 8,
          size: 100,
          blur: 40,
          offsetX: 80,
          offsetY: 50,
        },
      },
    },
  },
  {
    id: 'sparkle-celebration',
    name: 'Sparkle',
    description: 'Celebratory sparkle accents',
    data: {
      ...DEFAULT_PRICING_CONFIG,
      decorations: {
        ...DEFAULT_PRICING_CONFIG.decorations,
        sparkles: {
          ...DEFAULT_PRICING_CONFIG.decorations.sparkles,
          enabled: true,
          count: 7,
          size: 10,
          sizeVariation: 60,
          opacity: 50,
          radialFade: 40,
          color: 'white',
          spread: 140,
        },
      },
    },
  },
  {
    id: 'rings-tech',
    name: 'Tech Rings',
    description: 'Concentric ring accents',
    data: {
      ...DEFAULT_PRICING_CONFIG,
      decorations: {
        ...DEFAULT_PRICING_CONFIG.decorations,
        rings: {
          ...DEFAULT_PRICING_CONFIG.decorations.rings,
          enabled: true,
          count: 3,
          startRadius: 50,
          gap: 25,
          strokeWidth: 1,
          opacity: 20,
          radialFade: 50,
          color: 'gray-300',
          arcAngle: 90,
        },
      },
    },
  },
  {
    id: 'noise-subtle',
    name: 'Subtle Noise',
    description: 'Grain texture overlay',
    data: {
      ...DEFAULT_PRICING_CONFIG,
      decorations: {
        ...DEFAULT_PRICING_CONFIG.decorations,
        noise: {
          ...DEFAULT_PRICING_CONFIG.decorations.noise,
          enabled: true,
          opacity: 6,
          scale: 1.5,
          radialFade: 70,
          blendMode: 'overlay',
        },
      },
    },
  },
  {
    id: 'premium-full',
    name: 'Premium Full',
    description: 'All effects combined',
    data: {
      ...DEFAULT_PRICING_CONFIG,
      radialFlare: {
        ...DEFAULT_PRICING_CONFIG.radialFlare,
        enabled: true,
        flare1: {
          ...DEFAULT_PRICING_CONFIG.radialFlare.flare1,
          enabled: true,
          color: 'gray-300',
          opacity: 15,
          size: 200,
          blur: 60,
          offsetX: 60,
          offsetY: -40,
        },
        flare2: {
          ...DEFAULT_PRICING_CONFIG.radialFlare.flare2,
          enabled: true,
          color: 'blue-500',
          opacity: 10,
          size: 140,
          blur: 45,
          offsetX: 30,
          offsetY: 0,
        },
        flare3: {
          ...DEFAULT_PRICING_CONFIG.radialFlare.flare3,
          enabled: false,
          color: 'sky-400',
          opacity: 8,
          size: 80,
          blur: 30,
          offsetX: 60,
          offsetY: 40,
        },
      },
      decorations: {
        ...DEFAULT_PRICING_CONFIG.decorations,
        noise: {
          ...DEFAULT_PRICING_CONFIG.decorations.noise,
          enabled: true,
          opacity: 4,
          scale: 1.5,
          radialFade: 80,
          blendMode: 'overlay',
        },
        sparkles: {
          ...DEFAULT_PRICING_CONFIG.decorations.sparkles,
          enabled: true,
          count: 5,
          size: 8,
          sizeVariation: 50,
          opacity: 35,
          radialFade: 50,
          color: 'white',
          spread: 120,
        },
        rings: {
          ...DEFAULT_PRICING_CONFIG.decorations.rings,
          enabled: false,
          count: 2,
          startRadius: 60,
          gap: 30,
          strokeWidth: 0.5,
          opacity: 12,
          radialFade: 60,
          color: 'gray-300',
          arcAngle: 75,
        },
      },
    },
  },
]
