/**
 * Biaxial Command Menu V3 Playground - Presets
 */

import type { Preset } from '@/components/ui/prod/base/control-panel'
import type { PlaygroundState } from './types'

// ============================================================================
// PRESET: Default
// ============================================================================

const DEFAULT_PRESET: Preset<PlaygroundState> = {
  id: 'default',
  name: 'Default',
  data: {
    config: {
      duration: 350,
      collapseDuration: 125,
      contentFadeDuration: 0,
      contentFadeDelay: 0,
      animationSync: {
        backdropMode: 'size',
        backdropDelay: 0,
        backdropDurationOffset: 0,
        animateMenuContainer: true,
        menuContainerDelay: 0,
        menuContainerDurationOffset: 100,
        backdropScaleStart: 1,
        expandOrigin: 'top',
      },
      inputHeight: 40,
      inputWidth: 240,
      panelWidth: 340,
      maxPanelHeight: 380,
      innerPaddingTop: 4,
      innerPaddingBottom: 4,
      innerPaddingLeft: 4,
      innerPaddingRight: 4,
      itemHeight: 46,
      itemGap: 4,
      itemPaddingX: 10,
      itemPaddingY: 0,
      itemBorderRadius: 12,
      itemHighlightBackground: 'quaternary',
      itemHoverBackground: 'tertiary',
      itemIconSize: 16,
      itemIconGap: 8,
      itemIconOpacity: 60,
      borderRadius: 18,
      menuBorderRadius: 18,
      menuTopBorderRadius: 0,
      syncMenuContainerRadius: true,
      menuContainerInset: 4,
      menuBorderWidth: 1,
      menuBorderColor: 'primary',
      contentTopOffset: 12,
      contentBottomOffset: 0,
      inputPaddingExpanded: 10,
      inputTopPaddingExpanded: 0,
      backdropTopOffset: 0,
      placeholder: 'Search...',
      showEmptyState: true,
      emptyStateMessage: 'No results found',
      appearance: {
        borderRadius: '2xl',
        shadow: '2xl',
        shine: 'shine-2-subtle',
        background: 'tertiary',
        gradient: 'subtle-depth-md',
        gradientColor: 'tertiary',
        squircle: true,
      },
      inputBackground: 'none',
      menuBackground: 'secondary',
      menuShine: 'none',
      menuOverflowGradient: true,
      menuOverflowGradientHeight: 24,
      gradientInsetTop: 0,
      gradientInsetBottom: 0,
      gradientInsetLeft: 0,
      gradientInsetRight: 9,
      scrollPaddingTop: 0,
      scrollPaddingBottom: 20,
      scrollbarMarginTop: 0,
      scrollbarMarginBottom: 4,
      syncGradientToScrollbar: true,
      debug: false,
      experimentalTopSection: true,
      topSectionDurationOffset: -100,
      topSectionDelay: 0,
    },
  },
}

// ============================================================================
// PRESET: Default 2
// ============================================================================

const DEFAULT_2_PRESET: Preset<PlaygroundState> = {
  id: 'default-2',
  name: 'Default 2',
  data: {
    config: {
      duration: 350,
      collapseDuration: 125,
      contentFadeDuration: 0,
      contentFadeDelay: 0,
      animationSync: {
        backdropMode: 'size',
        backdropDelay: 0,
        backdropDurationOffset: 0,
        animateMenuContainer: true,
        menuContainerDelay: 0,
        menuContainerDurationOffset: 100,
        backdropScaleStart: 1,
        expandOrigin: 'top',
      },
      inputHeight: 40,
      inputWidth: 340,
      panelWidth: 440,
      maxPanelHeight: 300,
      innerPaddingTop: 4,
      innerPaddingBottom: 12,
      innerPaddingLeft: 4,
      innerPaddingRight: 4,
      itemHeight: 46,
      itemGap: 4,
      itemsTopGap: 10,
      itemPaddingX: 10,
      itemPaddingY: 0,
      itemBorderRadius: 12,
      itemHighlightBackground: 'quaternary',
      itemHoverBackground: 'tertiary',
      itemIconSize: 16,
      itemIconGap: 8,
      itemIconOpacity: 60,
      borderRadius: 18,
      menuBorderRadius: 18,
      menuTopBorderRadius: 0,
      syncMenuContainerRadius: true,
      menuContainerInset: 4,
      menuBorderWidth: 1,
      menuBorderColor: 'primary',
      contentTopOffset: 12,
      contentBottomOffset: 0,
      inputPaddingExpanded: 10,
      inputTopPaddingExpanded: 0,
      backdropTopOffset: 0,
      placeholder: 'Search...',
      showEmptyState: true,
      emptyStateMessage: 'No results found',
      appearance: {
        borderRadius: '2xl',
        shadow: '2xl',
        shine: 'shine-2-subtle',
        background: 'tertiary',
        gradient: 'subtle-depth-md',
        gradientColor: 'tertiary',
        squircle: true,
      },
      inputBackground: 'none',
      menuBackground: 'secondary',
      menuShine: 'none',
      menuOverflowGradient: true,
      menuOverflowGradientHeight: 24,
      gradientInsetTop: 0,
      gradientInsetBottom: 0,
      gradientInsetLeft: 0,
      gradientInsetRight: 9,
      scrollPaddingTop: 0,
      scrollPaddingBottom: 0,
      scrollbarMarginTop: 0,
      scrollbarMarginBottom: 4,
      syncGradientToScrollbar: true,
      debug: false,
      experimentalTopSection: true,
      topSectionDurationOffset: -100,
      topSectionDelay: 0,
      topSectionShine: 'shine-2-subtle',
      topSectionBorderWidth: 0,
      topSectionBackground: 'secondary',
      topSectionContent: 'custom',
      topSectionHeight: 80,
      topSectionBottomOffset: 16,
    },
  },
}

// ============================================================================
// EXPORTS
// ============================================================================

export const PRESETS: Preset<PlaygroundState>[] = [
  DEFAULT_PRESET,
  DEFAULT_2_PRESET,
]

export const DEFAULT_STATE: PlaygroundState = PRESETS[0]!.data
