/**
 * Biaxial Command Menu V2 Playground - Presets
 */

import type { Preset } from '@/components/ui/prod/base/control-panel'
import type { PlaygroundState } from './types'
import { DEFAULT_ANIMATION_SYNC } from '../core/constants'

// ============================================================================
// PRESETS
// ============================================================================

export const PRESETS: Preset<PlaygroundState>[] = [
  {
    id: 'default',
    name: 'Default',
    data: {
      config: {
        duration: 500,
        collapseDuration: 125,
        contentFadeDuration: 0,
        contentFadeDelay: 0,
        animationSync: {
          backdropMode: 'size',
          backdropDelay: 0,
          backdropDurationOffset: 0,
          animateMenuContainer: true,
          menuContainerDelay: 0,
          menuContainerDurationOffset: 100,
          backdropScaleStart: 1,
          expandOrigin: 'top',
        },
        inputHeight: 40,
        inputWidth: 240,
        panelWidth: 320,
        maxPanelHeight: 380,
        innerPaddingTop: 4,
        innerPaddingBottom: 4,
        innerPaddingLeft: 4,
        innerPaddingRight: 4,
        itemHeight: 36,
        itemGap: 2,
        itemsTopGap: 0,
        borderRadius: 18,
        menuBorderRadius: 18,
        menuTopBorderRadius: 0,
        syncMenuContainerRadius: true,
        menuContainerInset: 3,
        menuBorderWidth: 1,
        menuBorderColor: 'primary',
        contentTopOffset: 6,
        contentBottomOffset: 0,
        inputPaddingExpanded: 0,
        inputTopPaddingExpanded: 0,
        backdropTopOffset: 12,
        placeholder: 'Search...',
        showEmptyState: true,
        emptyStateMessage: 'No results found',
        appearance: {
          borderRadius: '2xl',
          shadow: '2xl',
          shine: 'shine-2-subtle',
          background: 'tertiary',
          gradient: 'subtle-depth-md',
          gradientColor: 'tertiary',
          squircle: true,
        },
        inputBackground: 'none',
        menuBackground: 'secondary',
        menuShine: 'none',
        menuOverflowGradient: true,
        menuOverflowGradientHeight: 24,
        gradientInsetTop: 0,
        gradientInsetBottom: 0,
        gradientInsetLeft: 0,
        gradientInsetRight: 9,
        scrollPaddingTop: 0,
        scrollPaddingBottom: 20,
        scrollbarMarginTop: 0,
        scrollbarMarginBottom: 4,
        syncGradientToScrollbar: true,
        debug: false,
      },
    },
  },
  {
    id: 'default-two',
    name: 'Default Two',
    data: {
      config: {
        duration: 350,
        collapseDuration: 125,
        contentFadeDuration: 0,
        contentFadeDelay: 0,
        animationSync: {
          backdropMode: 'size',
          backdropDelay: 0,
          backdropDurationOffset: 0,
          animateMenuContainer: true,
          menuContainerDelay: 0,
          menuContainerDurationOffset: 100,
          backdropScaleStart: 1,
          expandOrigin: 'top',
        },
        inputHeight: 40,
        inputWidth: 240,
        panelWidth: 340,
        maxPanelHeight: 380,
        innerPaddingTop: 4,
        innerPaddingBottom: 4,
        innerPaddingLeft: 4,
        innerPaddingRight: 4,
        itemHeight: 46,
        itemGap: 4,
        itemsTopGap: 0,
        borderRadius: 18,
        menuBorderRadius: 18,
        menuTopBorderRadius: 0,
        syncMenuContainerRadius: true,
        menuContainerInset: 4,
        menuBorderWidth: 1,
        menuBorderColor: 'primary',
        contentTopOffset: 12,
        contentBottomOffset: 0,
        inputPaddingExpanded: 10,
        inputTopPaddingExpanded: 0,
        backdropTopOffset: 0,
        placeholder: 'Search...',
        showEmptyState: true,
        emptyStateMessage: 'No results found',
        appearance: {
          borderRadius: '2xl',
          shadow: '2xl',
          shine: 'shine-2-subtle',
          background: 'tertiary',
          gradient: 'subtle-depth-md',
          gradientColor: 'tertiary',
          squircle: true,
        },
        inputBackground: 'none',
        menuBackground: 'secondary',
        menuShine: 'none',
        menuOverflowGradient: true,
        menuOverflowGradientHeight: 24,
        gradientInsetTop: 0,
        gradientInsetBottom: 0,
        gradientInsetLeft: 0,
        gradientInsetRight: 9,
        scrollPaddingTop: 0,
        scrollPaddingBottom: 20,
        scrollbarMarginTop: 0,
        scrollbarMarginBottom: 4,
        syncGradientToScrollbar: true,
        debug: false,
      },
    },
  },
]

// ============================================================================
// DEFAULT STATE
// ============================================================================

export const DEFAULT_STATE: PlaygroundState = PRESETS[0]!.data
