import type { SlideCardPresetMeta, SlideCardConfig } from './types'

/**
 * SlideCard Presets
 *
 * Preset categories:
 * - default: Current deck standard
 * - minimal: Clean, understated
 * - elevated: Premium, with depth effects
 * - brand: Uses brand colors and effects
 * - glass: Translucent glassmorphism
 * - custom: User-defined variations
 */

export const DEFAULT_SLIDECARD_CONFIG: SlideCardConfig = {
  card: {
    background: 'tertiary',
    backgroundGradient: true,
    gradientFrom: 'tertiary',
    gradientTo: 'quaternary',
    shine: 'shine-1',
    shineIntensity: '',
    shadow: 'none',
    depth: 'none',
    corner: 'squircle',
    borderRadius: 16,
    padding: 24,
    border: false,
    borderColor: 'primary',
    borderWidth: 1,
  },
  animation: {
    enabled: true,
    type: 'scale',
    duration: 500,
    delay: 200,
    easing: 'easeOut',
  },
  content: {
    type: 'chart',
    showPlaceholder: true,
    chartTopPadding: 40,
    barColor: 'secondary',
    barShine: 'shine-1',
    barCorner: 'squircle',
  },
  layout: {
    width: 'auto',
    minWidth: 200,
    maxWidth: 800,
    height: 'auto',
    minHeight: 100,
  },
}

export const SLIDECARD_PRESETS: SlideCardPresetMeta[] = [
  {
    id: 'default',
    name: 'Default Deck',
    category: 'default',
    description: 'Current PAYVA deck style',
    data: DEFAULT_SLIDECARD_CONFIG,
  },
  {
    id: 'clean-bordered',
    name: 'Clean Bordered',
    category: 'minimal',
    description: 'Clean card with subtle border',
    data: {
      card: {
        background: 'tertiary',
        backgroundGradient: false,
        gradientFrom: 'transparent',
        gradientTo: 'transparent',
        shine: 'none',
        shineIntensity: '',
        shadow: 'none',
        depth: 'none',
        corner: 'squircle',
        borderRadius: 40,
        padding: 28,
        border: true,
        borderColor: 'secondary',
        borderWidth: 1,
      },
      animation: {
        enabled: true,
        type: 'scale',
        duration: 500,
        delay: 200,
        easing: 'easeOut',
      },
      content: {
        type: 'chart',
        showPlaceholder: true,
        chartTopPadding: 50,
        barColor: 'gray-500',
        barShine: 'none',
        barCorner: 'squircle',
      },
      layout: {
        width: 'auto',
        minWidth: 200,
        maxWidth: 800,
        height: 'auto',
        minHeight: 100,
      },
    },
  },
  {
    id: 'minimal',
    name: 'Minimal',
    category: 'minimal',
    description: 'Clean, no effects',
    data: {
      card: {
        background: 'secondary',
        backgroundGradient: false,
        gradientFrom: 'secondary',
        gradientTo: 'secondary',
        shine: 'none',
        shineIntensity: '',
        shadow: 'none',
        depth: 'none',
        corner: 'round',
        borderRadius: 8,
        padding: 16,
        border: true,
        borderColor: 'tertiary',
        borderWidth: 1,
      },
      animation: {
        enabled: false,
        type: 'fade',
        duration: 300,
        delay: 0,
        easing: 'easeOut',
      },
      content: {
        type: 'stat',
        showPlaceholder: true,
        barColor: 'secondary',
        barShine: 'shine-1',
        barCorner: 'squircle',
      },
      layout: {
        width: 'auto',
        minWidth: 200,
        maxWidth: 800,
        height: 'auto',
        minHeight: 100,
      },
    },
  },
  {
    id: 'elevated',
    name: 'Elevated',
    category: 'elevated',
    description: 'Premium card with depth',
    data: {
      card: {
        background: 'secondary',
        backgroundGradient: false,
        gradientFrom: 'secondary',
        gradientTo: 'tertiary',
        shine: 'shine-2',
        shineIntensity: '-subtle',
        shadow: 'lg',
        depth: 'depth-gradient-2',
        corner: 'squircle',
        borderRadius: 24,
        padding: 32,
        border: false,
        borderColor: 'primary',
        borderWidth: 1,
      },
      animation: {
        enabled: true,
        type: 'slideUp',
        duration: 600,
        delay: 100,
        easing: 'spring',
      },
      content: {
        type: 'stat',
        showPlaceholder: true,
        barColor: 'secondary',
        barShine: 'shine-1',
        barCorner: 'squircle',
      },
      layout: {
        width: 'auto',
        minWidth: 250,
        maxWidth: 800,
        height: 'auto',
        minHeight: 150,
      },
    },
  },
  {
    id: 'brand-solid',
    name: 'Brand Solid',
    category: 'brand',
    description: 'Solid brand background',
    data: {
      card: {
        background: 'brand-solid',
        backgroundGradient: false,
        gradientFrom: 'brand-solid',
        gradientTo: 'brand-solid',
        shine: 'shine-brand',
        shineIntensity: '',
        shadow: 'md',
        depth: 'none',
        corner: 'squircle',
        borderRadius: 20,
        padding: 24,
        border: false,
        borderColor: 'brand',
        borderWidth: 2,
      },
      animation: {
        enabled: true,
        type: 'scale',
        duration: 400,
        delay: 150,
        easing: 'easeInOut',
      },
      content: {
        type: 'team',
        showPlaceholder: true,
        barColor: 'brand-primary',
        barShine: 'shine-brand',
        barCorner: 'squircle',
      },
      layout: {
        width: 'auto',
        minWidth: 200,
        maxWidth: 800,
        height: 'auto',
        minHeight: 100,
      },
    },
  },
  {
    id: 'glass',
    name: 'Glass',
    category: 'glass',
    description: 'Translucent glassmorphism',
    data: {
      card: {
        background: 'primary',
        backgroundGradient: false,
        gradientFrom: 'primary',
        gradientTo: 'secondary',
        shine: 'shine-3',
        shineIntensity: '-intense',
        shadow: 'xl',
        depth: 'depth-gradient-1',
        corner: 'round',
        borderRadius: 16,
        padding: 20,
        border: true,
        borderColor: 'secondary',
        borderWidth: 1,
      },
      animation: {
        enabled: true,
        type: 'fade',
        duration: 500,
        delay: 100,
        easing: 'easeOut',
      },
      content: {
        type: 'logo',
        showPlaceholder: true,
        barColor: 'slate-600',
        barShine: 'shine-3',
        barCorner: 'bevel',
      },
      layout: {
        width: 'auto',
        minWidth: 200,
        maxWidth: 800,
        height: 'auto',
        minHeight: 100,
      },
    },
  },
  {
    id: 'financial-chart',
    name: 'Financial Chart',
    category: 'custom',
    description: 'Optimized for chart displays',
    data: {
      card: {
        background: 'tertiary',
        backgroundGradient: true,
        gradientFrom: 'tertiary',
        gradientTo: 'quaternary',
        shine: 'shine-1',
        shineIntensity: '',
        shadow: 'none',
        depth: 'none',
        corner: 'squircle',
        borderRadius: 16,
        padding: 40,
        border: false,
        borderColor: 'primary',
        borderWidth: 1,
      },
      animation: {
        enabled: true,
        type: 'scale',
        duration: 500,
        delay: 300,
        easing: 'easeOut',
      },
      content: {
        type: 'chart',
        showPlaceholder: true,
        chartTopPadding: 45,
        barColor: 'gray-600',
        barShine: 'shine-1',
        barCorner: 'squircle',
      },
      layout: {
        width: 'fixed',
        minWidth: 500,
        maxWidth: 600,
        height: 'fixed',
        minHeight: 300,
      },
    },
  },
]

export const getPresetById = (id: string): SlideCardPresetMeta | undefined =>
  SLIDECARD_PRESETS.find((p) => p.id === id)

export const getPresetsByCategory = (category: string): SlideCardPresetMeta[] =>
  SLIDECARD_PRESETS.filter((p) => p.category === category)