/**
 * Origin Images Comparison - Panel Configuration
 */

import type { PanelConfig } from '@/components/ui/patterns/control-panel'
import type { OriginImagesConfig, OriginImagesPresetMeta } from '../config/types'

export function buildPanelConfig(
  config: OriginImagesConfig,
  presets: OriginImagesPresetMeta[],
  activePresetId: string | null,
): PanelConfig {
  return {
    title: 'Image Comparison',
    showReset: true,
    resetLabel: 'Reset',
    presetConfig: {
      presets: presets.map((p) => ({ id: p.id, name: p.name, data: p.data })),
      activePresetId,
      showCopyButton: true,
    },
    sections: [
      {
        id: 'display',
        label: 'Display',
        title: 'Display Mode',
        groups: [
          {
            title: 'Mode',
            controls: [
              {
                id: 'displayMode',
                type: 'select',
                label: 'Mode',
                value: config.displayMode,
                options: [
                  { label: 'Asset Card', value: 'card' },
                  { label: 'Comparison', value: 'comparison' },
                ],
              },
              ...(config.displayMode === 'card'
                ? [
                    {
                      id: 'cardImageType',
                      type: 'select' as const,
                      label: 'Image type',
                      value: config.cardImageType,
                      options: [
                        { label: 'Poster', value: 'poster' },
                        { label: 'Logo', value: 'logo' },
                        { label: 'Backdrop', value: 'backdrop' },
                      ],
                    },
                    {
                      id: 'showBackdropBehind',
                      type: 'toggle' as const,
                      label: 'Backdrop behind',
                      value: config.showBackdropBehind,
                    },
                    ...(config.showBackdropBehind
                      ? [
                          {
                            id: 'backdropShine',
                            type: 'select' as const,
                            label: 'Backdrop shine',
                            value: config.backdropShine,
                            options: [
                              { label: 'None', value: 'none' },
                              { label: '0 Subtle', value: 'shine-0-subtle' },
                              { label: '0', value: 'shine-0' },
                              { label: '0 + Shadow SM', value: 'shine-0-shadow-sm' },
                              { label: '0 + Shadow MD', value: 'shine-0-shadow-md' },
                              { label: '1 Subtle', value: 'shine-1-subtle' },
                              { label: '1', value: 'shine-1' },
                              { label: '1 + Shadow SM', value: 'shine-1-shadow-sm' },
                              { label: '1 + Shadow MD', value: 'shine-1-shadow-md' },
                              { label: '2 Subtle', value: 'shine-2-subtle' },
                              { label: '2', value: 'shine-2' },
                              { label: '2 + Shadow SM', value: 'shine-2-shadow-sm' },
                              { label: '2 + Shadow MD', value: 'shine-2-shadow-md' },
                              { label: '3 Subtle', value: 'shine-3-subtle' },
                              { label: '3', value: 'shine-3' },
                              { label: '3 + Shadow SM', value: 'shine-3-shadow-sm' },
                              { label: '3 + Shadow MD', value: 'shine-3-shadow-md' },
                              { label: 'Brand Subtle', value: 'shine-brand-subtle' },
                              { label: 'Brand', value: 'shine-brand' },
                              { label: 'Brand + Shadow MD', value: 'shine-brand-shadow-md' },
                            ],
                          },
                          {
                            id: 'backdropOpacity',
                            type: 'inline-slider' as const,
                            label: 'Backdrop opacity',
                            value: config.backdropOpacity,
                            min: 0,
                            max: 1,
                            step: 0.05,
                            formatLabel: (v: number) => `${Math.round(v * 100)}%`,
                          },
                          {
                            id: 'backdropPaddingX',
                            type: 'inline-slider' as const,
                            label: 'Container pad X',
                            value: config.backdropPaddingX,
                            min: 0,
                            max: 48,
                            step: 2,
                            formatLabel: (v: number) => `${v}px`,
                          },
                          {
                            id: 'backdropPaddingY',
                            type: 'inline-slider' as const,
                            label: 'Container pad Y',
                            value: config.backdropPaddingY,
                            min: 0,
                            max: 48,
                            step: 2,
                            formatLabel: (v: number) => `${v}px`,
                          },
                        ]
                      : []),
                  ]
                : []),
            ],
          },
          ...(config.displayMode === 'comparison'
            ? [
                {
                  title: 'Show / hide',
                  controls: [
                    {
                      id: 'showPoster',
                      type: 'toggle' as const,
                      label: 'Posters',
                      value: config.showPoster,
                    },
                    {
                      id: 'showLogo',
                      type: 'toggle' as const,
                      label: 'Logos',
                      value: config.showLogo,
                    },
                    {
                      id: 'showBackdrop',
                      type: 'toggle' as const,
                      label: 'Backdrops',
                      value: config.showBackdrop,
                    },
                    {
                      id: 'logoBg',
                      type: 'toggle' as const,
                      label: 'Logo background',
                      value: config.logoBg,
                    },
                  ],
                },
              ]
            : []),
          {
            title: 'Logo',
            controls: [
              {
                id: 'logoBg',
                type: 'toggle' as const,
                label: 'Logo background',
                value: config.logoBg,
              },
              ...(config.logoBg
                ? [
                    {
                      id: 'logoBgColor',
                      type: 'select' as const,
                      label: 'Background',
                      value: config.logoBgColor,
                      options: [
                        // Semantic colors (theme-aware)
                        { label: 'Tertiary', value: 'bg-tertiary' },
                        { label: 'Secondary', value: 'bg-secondary' },
                        { label: 'Secondary Alt', value: 'bg-secondary_alt' },
                        { label: 'Secondary Subtle', value: 'bg-secondary_subtle' },
                        { label: 'Primary', value: 'bg-primary' },
                        { label: 'Primary Alt', value: 'bg-primary_alt' },
                        { label: 'Quaternary', value: 'bg-quaternary' },
                        { label: 'Active', value: 'bg-active' },
                        { label: 'Brand Primary', value: 'bg-brand-primary' },
                        { label: 'Brand Section', value: 'bg-brand-section_subtle' },
                        { label: 'Inverted Primary', value: 'bg-inverted-primary' },
                        { label: 'Inverted Secondary', value: 'bg-inverted-secondary' },
                        { label: 'Inverted Tertiary', value: 'bg-inverted-tertiary' },
                        // Fixed grays (theme-agnostic)
                        { label: 'Gray 50', value: 'bg-gray-50' },
                        { label: 'Gray 100', value: 'bg-gray-100' },
                        { label: 'Gray 200', value: 'bg-gray-200' },
                        { label: 'Gray 300', value: 'bg-gray-300' },
                        { label: 'Gray 400', value: 'bg-gray-400' },
                        { label: 'Gray 500', value: 'bg-gray-500' },
                        { label: 'Gray 600', value: 'bg-gray-600' },
                        { label: 'Gray 700', value: 'bg-gray-700' },
                        { label: 'Gray 800', value: 'bg-gray-800' },
                        { label: 'Gray 900', value: 'bg-gray-900' },
                        { label: 'Gray 950', value: 'bg-gray-950' },
                      ],
                    },
                    {
                      id: 'logoPaddingX',
                      type: 'inline-slider' as const,
                      label: 'Logo pad X',
                      value: config.logoPaddingX,
                      min: 0,
                      max: 24,
                      step: 1,
                      formatLabel: (v: number) => `${v}px`,
                    },
                    {
                      id: 'logoPaddingY',
                      type: 'inline-slider' as const,
                      label: 'Logo pad Y',
                      value: config.logoPaddingY,
                      min: 0,
                      max: 24,
                      step: 1,
                      formatLabel: (v: number) => `${v}px`,
                    },
                    {
                      id: 'logoShine',
                      type: 'select' as const,
                      label: 'Shine',
                      value: config.logoShine,
                      options: [
                        { label: 'None', value: 'none' },
                        { label: '0 Subtle', value: 'shine-0-subtle' },
                        { label: '0', value: 'shine-0' },
                        { label: '0 + Shadow SM', value: 'shine-0-shadow-sm' },
                        { label: '0 + Shadow MD', value: 'shine-0-shadow-md' },
                        { label: '1 Subtle', value: 'shine-1-subtle' },
                        { label: '1', value: 'shine-1' },
                        { label: '1 + Shadow SM', value: 'shine-1-shadow-sm' },
                        { label: '1 + Shadow MD', value: 'shine-1-shadow-md' },
                        { label: '2 Subtle', value: 'shine-2-subtle' },
                        { label: '2', value: 'shine-2' },
                        { label: '2 + Shadow SM', value: 'shine-2-shadow-sm' },
                        { label: '2 + Shadow MD', value: 'shine-2-shadow-md' },
                        { label: '3 Subtle', value: 'shine-3-subtle' },
                        { label: '3', value: 'shine-3' },
                        { label: '3 + Shadow SM', value: 'shine-3-shadow-sm' },
                        { label: '3 + Shadow MD', value: 'shine-3-shadow-md' },
                        { label: 'Brand Subtle', value: 'shine-brand-subtle' },
                        { label: 'Brand', value: 'shine-brand' },
                        { label: 'Brand + Shadow MD', value: 'shine-brand-shadow-md' },
                      ],
                    },
                    {
                      id: 'logoSquircle',
                      type: 'toggle' as const,
                      label: 'Corner squircle',
                      value: config.logoSquircle,
                    },
                    {
                      id: 'logoInvert',
                      type: 'inline-slider' as const,
                      label: 'Invert',
                      value: config.logoInvert,
                      min: 0,
                      max: 1,
                      step: 0.05,
                      formatLabel: (v: number) => `${Math.round(v * 100)}%`,
                    },
                  ]
                : []),
              {
                id: 'logoOutline',
                type: 'toggle' as const,
                label: 'Logo outline',
                value: config.logoOutline,
              },
              ...(config.logoOutline
                ? [
                    {
                      id: 'logoOutlineColor',
                      type: 'select' as const,
                      label: 'Outline color',
                      value: config.logoOutlineColor,
                      options: [
                        { label: 'Auto (theme)', value: 'auto' },
                        { label: 'Dark', value: 'dark' },
                        { label: 'Light', value: 'light' },
                        { label: 'Brand', value: 'brand' },
                        { label: 'Subtle', value: 'subtle' },
                      ],
                    },
                    {
                      id: 'logoOutlineSize',
                      type: 'inline-slider' as const,
                      label: 'Outline size',
                      value: config.logoOutlineSize,
                      min: 0.5,
                      max: 4,
                      step: 0.5,
                      formatLabel: (v: number) => `${v}px`,
                    },
                    {
                      id: 'logoOutlineOpacity',
                      type: 'inline-slider' as const,
                      label: 'Outline opacity',
                      value: config.logoOutlineOpacity,
                      min: 0,
                      max: 1,
                      step: 0.05,
                      formatLabel: (v: number) => `${Math.round(v * 100)}%`,
                    },
                    {
                      id: 'logoOutlineIntensity',
                      type: 'inline-slider' as const,
                      label: 'Intensity',
                      value: config.logoOutlineIntensity,
                      min: 1,
                      max: 3,
                      step: 1,
                      formatLabel: (v: number) => `${v}x`,
                    },
                    {
                      id: 'logoOutlineDual',
                      type: 'toggle' as const,
                      label: 'Dual layer (dark + light)',
                      value: config.logoOutlineDual,
                    },
                  ]
                : []),
            ],
          },
          {
            title: 'Labels',
            controls: [
              {
                id: 'showLabel',
                type: 'toggle' as const,
                label: 'Show name',
                value: config.showLabel,
              },
              ...(config.showLabel
                ? [
                    {
                      id: 'labelPosition',
                      type: 'select' as const,
                      label: 'Position',
                      value: config.labelPosition,
                      options: [
                        { label: 'Bottom', value: 'bottom' },
                        { label: 'Right', value: 'right' },
                      ],
                    },
                    {
                      id: 'labelGap',
                      type: 'inline-slider' as const,
                      label: 'Label gap',
                      value: config.labelGap,
                      min: 0,
                      max: 24,
                      step: 1,
                      formatLabel: (v: number) => `${v}px`,
                    },
                    {
                      id: 'labelColor',
                      type: 'select' as const,
                      label: 'Color',
                      value: config.labelColor,
                      options: [
                        { label: 'Primary', value: 'text-primary' },
                        { label: 'Secondary', value: 'text-secondary' },
                        { label: 'Tertiary', value: 'text-tertiary' },
                        { label: 'Brand', value: 'text-brand' },
                        { label: 'Inverted Primary', value: 'text-inverted-primary' },
                        { label: 'Inverted Secondary', value: 'text-inverted-secondary' },
                      ],
                    },
                    {
                      id: 'labelOpacity',
                      type: 'inline-slider' as const,
                      label: 'Opacity',
                      value: config.labelOpacity,
                      min: 0,
                      max: 1,
                      step: 0.05,
                      formatLabel: (v: number) => `${Math.round(v * 100)}%`,
                    },
                    {
                      id: 'labelWeight',
                      type: 'inline-slider' as const,
                      label: 'Weight',
                      value: config.labelWeight,
                      min: 100,
                      max: 900,
                      step: 100,
                    },
                  ]
                : []),
            ],
          },
        ],
      },
      {
        id: 'sizing',
        label: 'Size',
        title: 'Thumbnail Size',
        groups: [
          {
            title: 'Dimensions',
            controls: [
              {
                id: 'width',
                type: 'inline-slider',
                label: 'Width',
                value: config.width,
                min: 12,
                max: 200,
                step: 4,
                formatLabel: (v: number) => `${v}px`,
              },
              {
                id: 'height',
                type: 'inline-slider',
                label: 'Height',
                value: config.height,
                min: 12,
                max: 200,
                step: 4,
                formatLabel: (v: number) => `${v}px`,
              },
              {
                id: 'borderRadius',
                type: 'inline-slider',
                label: 'Radius',
                value: config.borderRadius,
                min: 0,
                max: 32,
                step: 1,
                formatLabel: (v: number) => `${v}px`,
              },
            ],
          },
        ],
      },
      {
        id: 'layout',
        label: 'Layout',
        title: 'Grid Layout',
        groups: [
          {
            title: 'Grid',
            controls: [
              {
                id: 'columns',
                type: 'inline-slider',
                label: 'Columns',
                value: config.columns,
                min: 1,
                max: 8,
                step: 1,
              },
              {
                id: 'gap',
                type: 'inline-slider',
                label: 'Gap',
                value: config.gap,
                min: 4,
                max: 48,
                step: 4,
                formatLabel: (v: number) => `${v}px`,
              },
              {
                id: 'paddingX',
                type: 'inline-slider',
                label: 'Padding X',
                value: config.paddingX,
                min: 0,
                max: 64,
                step: 4,
                formatLabel: (v: number) => `${v}px`,
              },
              {
                id: 'paddingY',
                type: 'inline-slider',
                label: 'Padding Y',
                value: config.paddingY,
                min: 0,
                max: 64,
                step: 4,
                formatLabel: (v: number) => `${v}px`,
              },
            ],
          },
        ],
      },
    ],
  }
}
