/**
 * Pricing Tiers Data
 *
 * Sample pricing tier data for the PricingSelectSlot component.
 */

import type { PricingTier } from '@/components/ui/features/pricing-select-menu'

export const PRICING_TIERS: PricingTier[] = [
  {
    id: 'tier-100',
    credits: 100,
    price: 19,
    multiplier: 1,
    planName: 'Pro',
    creditsLabel: '100 credits / month',
    label: '100 credits / month',
    priceLabel: '$19/mo',
    eventsPerMonth: 1000000,
    eventsLabel: '1,000,000 events/mo',
    planNameShort: '1m plan',
    priceFormatted: '$19.00',
    monthlyPrice: 19,
    recurringText: 'Then $19.00/mo. Cancel anytime.',
    additionalCredits: 0,
    additionalCreditsLabel: '',
    upgradeFee: 0,
    upgradeFeeFormatted: '$0.00',
    upgradeFeeLabel: '$0',
  },
  {
    id: 'tier-200',
    credits: 200,
    price: 39,
    multiplier: 2,
    planName: 'Pro 2x',
    creditsLabel: '200 credits / month',
    label: '200 credits / month',
    priceLabel: '$39/mo',
    eventsPerMonth: 2000000,
    eventsLabel: '2,000,000 events/mo',
    planNameShort: '2m plan',
    priceFormatted: '$39.00',
    monthlyPrice: 39,
    recurringText: 'Then $39.00/mo. Cancel anytime.',
    additionalCredits: 100,
    additionalCreditsLabel: '+100 additional credits',
    upgradeFee: 20,
    upgradeFeeFormatted: '$20.00',
    upgradeFeeLabel: '$20',
  },
  {
    id: 'tier-300',
    credits: 300,
    price: 59,
    multiplier: 3,
    planName: 'Pro 3x',
    creditsLabel: '300 credits / month',
    label: '300 credits / month',
    priceLabel: '$59/mo',
    eventsPerMonth: 5000000,
    eventsLabel: '5,000,000 events/mo',
    planNameShort: '5m plan',
    priceFormatted: '$59.00',
    monthlyPrice: 59,
    recurringText: 'Then $59.00/mo. Cancel anytime.',
    additionalCredits: 200,
    additionalCreditsLabel: '+200 additional credits',
    upgradeFee: 40,
    upgradeFeeFormatted: '$40.00',
    upgradeFeeLabel: '$40',
  },
  {
    id: 'tier-400',
    credits: 400,
    price: 79,
    multiplier: 4,
    planName: 'Pro 4x',
    creditsLabel: '400 credits / month',
    label: '400 credits / month',
    priceLabel: '$79/mo',
    eventsPerMonth: 10000000,
    eventsLabel: '10,000,000 events/mo',
    planNameShort: '10m plan',
    priceFormatted: '$79.00',
    monthlyPrice: 79,
    recurringText: 'Then $79.00/mo. Cancel anytime.',
    additionalCredits: 300,
    additionalCreditsLabel: '+300 additional credits',
    upgradeFee: 60,
    upgradeFeeFormatted: '$60.00',
    upgradeFeeLabel: '$60',
  },
  {
    id: 'tier-500',
    credits: 500,
    price: 99,
    multiplier: 5,
    planName: 'Pro 5x',
    creditsLabel: '500 credits / month',
    label: '500 credits / month',
    priceLabel: '$99/mo',
    eventsPerMonth: 25000000,
    eventsLabel: '25,000,000 events/mo',
    planNameShort: '25m plan',
    priceFormatted: '$99.00',
    monthlyPrice: 99,
    recurringText: 'Then $99.00/mo. Cancel anytime.',
    additionalCredits: 400,
    additionalCreditsLabel: '+400 additional credits',
    upgradeFee: 80,
    upgradeFeeFormatted: '$80.00',
    upgradeFeeLabel: '$80',
  },
  {
    id: 'tier-600',
    credits: 600,
    price: 119,
    multiplier: 6,
    planName: 'Pro 6x',
    creditsLabel: '600 credits / month',
    label: '600 credits / month',
    priceLabel: '$119/mo',
    eventsPerMonth: 50000000,
    eventsLabel: '50,000,000 events/mo',
    planNameShort: '50m plan',
    priceFormatted: '$119.00',
    monthlyPrice: 119,
    recurringText: 'Then $119.00/mo. Cancel anytime.',
    additionalCredits: 500,
    additionalCreditsLabel: '+500 additional credits',
    upgradeFee: 100,
    upgradeFeeFormatted: '$100.00',
    upgradeFeeLabel: '$100',
  },
]
