/**
 * BiaxialExpand Playground Presets
 *
 * Preset categories:
 * - default: Balanced settings for general use
 * - use-case: Specific implementations (command menu, metric card)
 * - minimal: Simplified configurations
 * - custom: User-defined variations
 */

import type { BiaxialExpandPresetMeta, BiaxialExpandPlaygroundConfig, VariantBConfig } from './types'

// ============================================================================
// DEFAULT VARIANT B CONFIG
// ============================================================================

export const DEFAULT_VARIANT_B_CONFIG: VariantBConfig = {
  trigger: {
    planRow: {
      show: true,
      leftText: '',                   // Uses tier.planName (Pro, Pro 2x, etc.)
      rightSource: 'additionalCredits', // "+100 credits" for upgrade flow
      leftFontSize: 'sm',
      leftFontWeight: 'medium',
      leftTextColor: 'primary',
      leftOpacity: '100',
      rightFontSize: 'sm',
      rightFontWeight: 'normal',
      rightTextColor: 'tertiary',
      rightOpacity: '60',
    },
    paddingX: 20,
    paddingTop: 16,
    paddingBottom: 12,
  },
  bottomSlot: {
    dueRow: {
      show: true,
      leftText: 'Due today',
      rightSource: 'upgradeFee',     // Upgrade fee (price difference from Pro)
      leftFontSize: 'sm',
      leftFontWeight: 'normal',
      leftTextColor: 'tertiary',
      leftOpacity: '100',
      rightFontSize: 'sm',
      rightFontWeight: 'semibold',
      rightTextColor: 'primary',
      rightOpacity: '100',
    },
    subtext: {
      show: true,
      template: 'Then {price}/mo. Cancel anytime.', // {price} = monthlyPrice (new recurring)
      fontSize: 'sm',
      fontWeight: 'normal',
      textColor: 'tertiary',
      opacity: '60',
    },
    rowGap: 4,
    paddingX: 16,
    paddingTop: 12,
    paddingBottom: 12,
  },
  transition: {
    enabled: false,
    type: 'spring',
    duration: 0.2,
    bounce: 0.1,
    yOffset: 2,
  },
  headerMode: 'shared',
  headerText: 'Upgrade fee',
}

// ============================================================================
// DEFAULT CONFIG
// ============================================================================

export const DEFAULT_BIAXIAL_EXPAND_PLAYGROUND_CONFIG: BiaxialExpandPlaygroundConfig = {
  layout: {
    triggerWidth: 280,
    triggerHeight: 44,
    triggerHeightB: 44,
    panelWidth: 380,
    maxTopHeight: 0,
    maxBottomHeight: 340,
    maxBottomHeightB: 340,
    maxLeftWidth: 120,
    maxRightWidth: 120,
    borderRadius: 20,
    topGap: 0,
    bottomGap: 12,
    leftGap: 0,
    rightGap: 0,
    backdropTopOffset: 0,
    expandOriginX: 'center',
    positionMode: 'overlay',
    syncTriggerWidth: false,
  },
  animation: {
    duration: 350,
    collapseDuration: 125,
    contentFadeDuration: 0,
    contentFadeDelay: 0,
    backdropMode: 'size',
    backdropDelay: 0,
    backdropDurationOffset: 0,
    animateSlotContainers: true,
    slotContainerDelay: 0,
    slotContainerDurationOffset: 100,
    expandOrigin: 'top',
    topExpandOrigin: 'bottom',
    leftExpandOrigin: 'right',
    rightExpandOrigin: 'left',
  },
  appearance: {
    borderRadius: '2xl',
    shadow: '2xl',
    shine: 'shine-2-subtle',
    background: 'tertiary',
    gradient: 'subtle-depth-md',
    gradientColor: 'tertiary',
    squircle: true,
  },
  topSlot: {
    enabled: false,
    heightMode: 'fixed',
    height: 48,
    drivesPanelHeight: false,
    background: 'secondary',
    shine: 'none',
    borderRadius: 14,
    inset: 4,
    borderWidth: 1,
    borderColor: 'primary',
  },
  bottomSlot: {
    enabled: true,
    heightMode: 'dynamic',
    height: 200,
    drivesPanelHeight: true,
    scrollable: false,
    background: 'secondary',
    shine: 'none',
    borderRadius: 14,
    inset: 4,
    borderWidth: 1,
    borderColor: 'primary',
  },
  leftSlot: {
    enabled: false,
    heightMode: 'fixed',
    height: 0,
    drivesPanelHeight: false,
    background: 'secondary',
    shine: 'none',
    borderRadius: 14,
    inset: 4,
    borderWidth: 1,
    borderColor: 'primary',
    maxHeight: 200,
    verticalAlign: 'top',
    drivingHeight: 200,
  },
  rightSlot: {
    enabled: false,
    heightMode: 'fixed',
    height: 0,
    drivesPanelHeight: false,
    background: 'secondary',
    shine: 'none',
    borderRadius: 14,
    inset: 4,
    borderWidth: 1,
    borderColor: 'primary',
    maxHeight: 200,
    verticalAlign: 'top',
    drivingHeight: 200,
  },
  trigger: {
    collapsed: {
      background: 'secondary',
      shine: 'none',
      borderRadius: 14,
      borderWidth: 1,
      borderColor: 'primary',
    },
    expanded: {
      background: 'secondary',
      shine: 'none',
      borderRadius: 14,
      borderWidth: 1,
      borderColor: 'primary',
    },
  },
  demo: {
    variant: 'command-menu',
    pageBackground: 'primary',
    showDebug: false,
    slowMo: false,
    debugContainer: {
      enabled: false,
      showLines: true,
      width: 500,
      padding: 10,
      fixedHeight: false,
      height: 300,
      header: {
        show: false,
        text: 'Select a plan',
        fontSize: 'sm',
        fontWeight: 'medium',
        textColor: 'primary',
        opacity: '100',
        marginBottom: 12,
      },
    },
  },
  selectMenu: {
    showDropdownIcon: true,
    dropdownIconRotates: true,
    triggerPaddingX: 16,
    triggerPaddingTop: 0,
    triggerPaddingBottom: 0,
    syncedSubtext: {
      syncWithSelection: false,
      separator: ' - ',
      gap: 0,
      planName: {
        show: true,
        displayMode: 'text',
        fontSize: 'xs',
        fontWeight: 'medium',
        textColor: 'primary',
        opacity: '100',
        badgeColor: 'brand',
      },
      credits: {
        show: true,
        displayMode: 'text',
        fontSize: 'xs',
        fontWeight: 'normal',
        textColor: 'tertiary',
        opacity: '60',
        badgeColor: 'gray',
      },
    },
    showHeader: false,
    headerLabel: 'Select plan',
    headerTextColor: 'tertiary',
    headerFontWeight: 'medium',
    headerFontSize: 'xs',
    headerOpacity: '100',
    headerUppercase: false,
    headerPaddingBottom: 8,
    containerPadding: 4,
    itemPaddingX: 12,
    itemPaddingY: 12,
    itemBorderRadius: 8,
    itemGap: 2,
    itemHoverBackground: 'quaternary',
    menuItemLabel: {
      layout: 'inline',
      separator: ' - ',
      gap: 0,
      planName: {
        show: true,
        displayMode: 'text',
        fontSize: 'sm',
        fontWeight: 'medium',
        textColor: 'primary',
        opacity: '100',
        badgeColor: 'brand',
      },
      credits: {
        show: true,
        displayMode: 'text',
        fontSize: 'sm',
        fontWeight: 'normal',
        textColor: 'tertiary',
        opacity: '60',
        badgeColor: 'gray',
      },
    },
    availableTiers: ['tier-100', 'tier-200', 'tier-300', 'tier-400', 'tier-500', 'tier-600'],
    upgradeMode: false,
    showSelectedIndicator: false,
    triggerTypography: {
      label: {
        text: 'Upgrade',
        show: true,
        fontSize: 'sm',
        fontWeight: 'semibold',
        textColor: 'primary',
      },
      price: {
        prefix: '$',
        show: true,
        fontSize: 'sm',
        fontWeight: 'semibold',
        textColor: 'primary',
      },
      priceSuffix: {
        text: 'per month',
        show: true,
        fontSize: 'xs',
        fontWeight: 'normal',
        textColor: 'tertiary',
        opacity: '60',
      },
      subtext: {
        text: '',
        show: false,
        fontSize: 'xs',
        fontWeight: 'normal',
        textColor: 'tertiary',
        opacity: '60',
      },
      priceRowAlign: 'baseline',
      priceRowGap: 4,
      rowGap: 2,
    },
    itemTypography: {
      label: {
        fontSize: 'sm',
        fontWeight: 'normal',
        textColor: 'primary',
      },
      price: {
        fontSize: 'sm',
        fontWeight: 'normal',
        textColor: 'tertiary',
        opacity: '100',
      },
    },
  },
  variantB: DEFAULT_VARIANT_B_CONFIG,
}

// ============================================================================
// PRESETS
// ============================================================================

export const BIAXIAL_EXPAND_PRESETS: BiaxialExpandPresetMeta[] = [
  {
    id: 'default',
    name: 'Default',
    category: 'default',
    description: 'Balanced settings for general use',
    data: DEFAULT_BIAXIAL_EXPAND_PLAYGROUND_CONFIG,
  },
  {
    id: 'command-menu',
    name: 'Command Menu',
    category: 'use-case',
    description: 'Full command menu with search and menu content',
    data: {
      ...DEFAULT_BIAXIAL_EXPAND_PLAYGROUND_CONFIG,
      layout: {
        ...DEFAULT_BIAXIAL_EXPAND_PLAYGROUND_CONFIG.layout,
        triggerWidth: 300,
        panelWidth: 420,
        maxBottomHeight: 380,
      },
      demo: {
        variant: 'command-menu',
        pageBackground: 'primary',
        showDebug: false,
        slowMo: false,
        debugContainer: {
          enabled: false,
          showLines: true,
          width: 500,
          padding: 10,
          fixedHeight: false,
          height: 300,
          header: DEFAULT_BIAXIAL_EXPAND_PLAYGROUND_CONFIG.demo.debugContainer.header,
        },
      },
    },
  },
  {
    id: 'command-menu-with-filters',
    name: 'Command Menu + Filters',
    category: 'use-case',
    description: 'Command menu with top filter bar',
    data: {
      ...DEFAULT_BIAXIAL_EXPAND_PLAYGROUND_CONFIG,
      layout: {
        ...DEFAULT_BIAXIAL_EXPAND_PLAYGROUND_CONFIG.layout,
        triggerWidth: 300,
        panelWidth: 420,
        maxTopHeight: 60,
        maxBottomHeight: 340,
        topGap: 8,
      },
      topSlot: {
        enabled: true,
        heightMode: 'fixed',
        height: 48,
        drivesPanelHeight: false,
        background: 'secondary',
        shine: 'none',
        borderRadius: 14,
        inset: 4,
        borderWidth: 1,
        borderColor: 'primary',
      },
      demo: {
        variant: 'command-menu',
        pageBackground: 'primary',
        showDebug: false,
        slowMo: false,
        debugContainer: {
          enabled: false,
          showLines: true,
          width: 500,
          padding: 10,
          fixedHeight: false,
          height: 300,
          header: DEFAULT_BIAXIAL_EXPAND_PLAYGROUND_CONFIG.demo.debugContainer.header,
        },
      },
    },
  },
  {
    id: 'dashboard-metric',
    name: 'Dashboard Metric',
    category: 'use-case',
    description: 'Metric card that expands to show details',
    data: {
      ...DEFAULT_BIAXIAL_EXPAND_PLAYGROUND_CONFIG,
      layout: {
        ...DEFAULT_BIAXIAL_EXPAND_PLAYGROUND_CONFIG.layout,
        triggerWidth: 200,
        triggerHeight: 80,
        panelWidth: 320,
        maxTopHeight: 0,
        maxBottomHeight: 200,
        borderRadius: 16,
        topGap: 0,
        bottomGap: 8,
        backdropTopOffset: 0,
      },
      animation: {
        ...DEFAULT_BIAXIAL_EXPAND_PLAYGROUND_CONFIG.animation,
        duration: 300,
        collapseDuration: 150,
      },
      appearance: {
        borderRadius: 'xl',
        shadow: 'lg',
        shine: 'shine-1-subtle',
        background: 'secondary',
        gradient: 'subtle-depth-sm',
        gradientColor: 'secondary',
        squircle: true,
      },
      bottomSlot: {
        enabled: true,
        heightMode: 'auto',
        height: 150,
        drivesPanelHeight: true,
        background: 'tertiary',
        shine: 'none',
        borderRadius: 12,
        inset: 4,
        borderWidth: 1,
        borderColor: 'secondary',
      },
      demo: {
        variant: 'dashboard-metric',
        pageBackground: 'primary',
        showDebug: false,
        slowMo: false,
        debugContainer: {
          enabled: false,
          showLines: true,
          width: 500,
          padding: 10,
          fixedHeight: false,
          height: 300,
          header: DEFAULT_BIAXIAL_EXPAND_PLAYGROUND_CONFIG.demo.debugContainer.header,
        },
      },
    },
  },
  {
    id: 'minimal',
    name: 'Minimal',
    category: 'minimal',
    description: 'Simplified with minimal styling',
    data: {
      ...DEFAULT_BIAXIAL_EXPAND_PLAYGROUND_CONFIG,
      layout: {
        ...DEFAULT_BIAXIAL_EXPAND_PLAYGROUND_CONFIG.layout,
        triggerWidth: 200,
        triggerHeight: 36,
        panelWidth: 280,
        maxTopHeight: 0,
        maxBottomHeight: 200,
        borderRadius: 12,
        topGap: 0,
        bottomGap: 8,
        backdropTopOffset: 0,
      },
      appearance: {
        borderRadius: 'lg',
        shadow: 'md',
        shine: 'none',
        background: 'secondary',
        gradient: 'none',
        gradientColor: 'secondary',
        squircle: false,
      },
      topSlot: {
        ...DEFAULT_BIAXIAL_EXPAND_PLAYGROUND_CONFIG.topSlot,
        enabled: false,
      },
      bottomSlot: {
        enabled: true,
        heightMode: 'auto',
        height: 150,
        drivesPanelHeight: true,
        background: 'none',
        shine: 'none',
        borderRadius: 8,
        inset: 0,
        borderWidth: 0,
        borderColor: 'primary',
      },
      demo: {
        variant: 'custom',
        pageBackground: 'primary',
        showDebug: false,
        slowMo: false,
        debugContainer: {
          enabled: false,
          showLines: true,
          width: 500,
          padding: 10,
          fixedHeight: false,
          height: 300,
          header: DEFAULT_BIAXIAL_EXPAND_PLAYGROUND_CONFIG.demo.debugContainer.header,
        },
      },
    },
  },
  {
    id: 'filter-dropdown',
    name: 'Filter Dropdown',
    category: 'use-case',
    description: 'Top slot focus with filter bar above trigger',
    data: {
      ...DEFAULT_BIAXIAL_EXPAND_PLAYGROUND_CONFIG,
      layout: {
        ...DEFAULT_BIAXIAL_EXPAND_PLAYGROUND_CONFIG.layout,
        triggerWidth: 180,
        triggerHeight: 40,
        panelWidth: 320,
        maxTopHeight: 200,
        maxBottomHeight: 0,
        borderRadius: 16,
        topGap: 8,
        bottomGap: 0,
        backdropTopOffset: 0,
      },
      topSlot: {
        enabled: true,
        heightMode: 'auto',
        height: 150,
        drivesPanelHeight: false,
        background: 'secondary',
        shine: 'none',
        borderRadius: 12,
        inset: 4,
        borderWidth: 1,
        borderColor: 'primary',
      },
      bottomSlot: {
        ...DEFAULT_BIAXIAL_EXPAND_PLAYGROUND_CONFIG.bottomSlot,
        enabled: false,
      },
      demo: {
        variant: 'custom',
        pageBackground: 'primary',
        showDebug: false,
        slowMo: false,
        debugContainer: {
          enabled: false,
          showLines: true,
          width: 500,
          padding: 10,
          fixedHeight: false,
          height: 300,
          header: DEFAULT_BIAXIAL_EXPAND_PLAYGROUND_CONFIG.demo.debugContainer.header,
        },
      },
    },
  },
  {
    id: 'horizontal-expand',
    name: 'Horizontal Expand',
    category: 'use-case',
    description: 'Trigger with left and right action slots',
    data: {
      ...DEFAULT_BIAXIAL_EXPAND_PLAYGROUND_CONFIG,
      layout: {
        ...DEFAULT_BIAXIAL_EXPAND_PLAYGROUND_CONFIG.layout,
        triggerWidth: 200,
        triggerHeight: 48,
        panelWidth: 280,
        maxLeftWidth: 80,
        maxRightWidth: 80,
        maxBottomHeight: 0,
        borderRadius: 16,
        leftGap: 8,
        rightGap: 8,
        bottomGap: 0,
      },
      bottomSlot: {
        ...DEFAULT_BIAXIAL_EXPAND_PLAYGROUND_CONFIG.bottomSlot,
        enabled: false,
      },
      leftSlot: {
        enabled: true,
        heightMode: 'fixed',
        height: 0,
        drivesPanelHeight: false,
        background: 'secondary',
        shine: 'none',
        borderRadius: 12,
        inset: 4,
        borderWidth: 1,
        borderColor: 'primary',
        maxHeight: 200,
        verticalAlign: 'top',
        drivingHeight: 200,
      },
      rightSlot: {
        enabled: true,
        heightMode: 'fixed',
        height: 0,
        drivesPanelHeight: false,
        background: 'secondary',
        shine: 'none',
        borderRadius: 12,
        inset: 4,
        borderWidth: 1,
        borderColor: 'primary',
        maxHeight: 200,
        verticalAlign: 'top',
        drivingHeight: 200,
      },
      demo: {
        variant: 'custom',
        pageBackground: 'primary',
        showDebug: false,
        slowMo: false,
        debugContainer: {
          enabled: false,
          showLines: true,
          width: 500,
          padding: 10,
          fixedHeight: false,
          height: 300,
          header: DEFAULT_BIAXIAL_EXPAND_PLAYGROUND_CONFIG.demo.debugContainer.header,
        },
      },
    },
  },
  {
    id: 'pricing-select',
    name: 'Pricing Select',
    category: 'use-case',
    description: 'Upgrade selector with pricing tiers',
    data: {
      ...DEFAULT_BIAXIAL_EXPAND_PLAYGROUND_CONFIG,
      layout: {
        triggerWidth: 200,
        triggerHeight: 88,
        triggerHeightB: 44,
        panelWidth: 320,
        maxTopHeight: 0,
        maxBottomHeight: 220,
        maxBottomHeightB: 80,
        maxLeftWidth: 120,
        maxRightWidth: 120,
        borderRadius: 16,
        topGap: 0,
        bottomGap: 0,
        leftGap: 0,
        rightGap: 0,
        backdropTopOffset: 0,
        expandOriginX: 'center',
        positionMode: 'overlay',
        syncTriggerWidth: true,
      },
      animation: {
        duration: 300,
        collapseDuration: 150,
        contentFadeDuration: 0,
        contentFadeDelay: 0,
        backdropMode: 'size',
        backdropDelay: 0,
        backdropDurationOffset: 0,
        animateSlotContainers: false,
        slotContainerDelay: 0,
        slotContainerDurationOffset: 100,
        expandOrigin: 'top',
        topExpandOrigin: 'bottom',
        leftExpandOrigin: 'right',
        rightExpandOrigin: 'left',
      },
      appearance: {
        borderRadius: 'xl',
        shadow: 'lg',
        shine: 'shine-1-subtle',
        background: 'secondary',
        gradient: 'subtle-depth-sm',
        gradientColor: 'secondary',
        squircle: false,
      },
      topSlot: {
        enabled: false,
        heightMode: 'fixed',
        height: 48,
        drivesPanelHeight: false,
        background: 'secondary',
        shine: 'none',
        borderRadius: 14,
        inset: 4,
        borderWidth: 1,
        borderColor: 'primary',
      },
      bottomSlot: {
        enabled: true,
        heightMode: 'dynamic',
        integratedHeightMode: 'auto',
        height: 160,
        integratedHeight: null,
        drivesPanelHeight: true,
        scrollable: true,
        background: 'primary',
        shine: 'none',
        borderRadius: 12,
        inset: 4,
        borderWidth: 1,
        borderColor: 'secondary',
      },
      leftSlot: {
        enabled: false,
        heightMode: 'fixed',
        height: 0,
        drivesPanelHeight: false,
        background: 'secondary',
        shine: 'none',
        borderRadius: 14,
        inset: 4,
        borderWidth: 1,
        borderColor: 'primary',
        maxHeight: 200,
        verticalAlign: 'top',
        drivingHeight: 200,
      },
      rightSlot: {
        enabled: false,
        heightMode: 'fixed',
        height: 0,
        drivesPanelHeight: false,
        background: 'secondary',
        shine: 'none',
        borderRadius: 14,
        inset: 4,
        borderWidth: 1,
        borderColor: 'primary',
        maxHeight: 200,
        verticalAlign: 'top',
        drivingHeight: 200,
      },
      trigger: {
        collapsed: {
          background: 'none',
          shine: 'none',
          borderRadius: 14,
          borderWidth: 0,
          borderColor: 'primary',
        },
        expanded: {
          background: 'none',
          shine: 'none',
          borderRadius: 14,
          borderWidth: 0,
          borderColor: 'primary',
        },
      },
      demo: {
        variant: 'pricing-select',
        pageBackground: 'primary',
        showDebug: false,
        slowMo: false,
        debugContainer: {
          enabled: true,
          showLines: true,
          width: 420,
          padding: 10,
          fixedHeight: true,
          height: 360,
          header: {
            show: true,
            text: 'Upgrade fee',
            fontSize: 'sm',
            fontWeight: 'medium',
            textColor: 'tertiary',
            opacity: '80',
            marginBottom: 12,
          },
        },
      },
      selectMenu: {
        showDropdownIcon: true,
        dropdownIconRotates: true,
        triggerPaddingX: 20,
        triggerPaddingTop: 0,
        triggerPaddingBottom: 0,
        syncedSubtext: {
          syncWithSelection: true,
          separator: '',
          gap: 4,
          planName: {
            show: true,
            displayMode: 'text',
            fontSize: 'xs',
            fontWeight: 'medium',
            textColor: 'tertiary',
            opacity: '100',
            badgeColor: 'brand',
          },
          credits: {
            show: true,
            displayMode: 'text',
            fontSize: 'xs',
            fontWeight: 'normal',
            textColor: 'tertiary',
            opacity: '60',
            badgeColor: 'gray',
          },
        },
        showHeader: true,
        headerLabel: 'Plans',
        headerTextColor: 'tertiary',
        headerFontWeight: 'medium',
        headerFontSize: 'xs',
        headerOpacity: '40',
        headerUppercase: false,
        headerPaddingBottom: 0,
        containerPadding: 4,
        itemPaddingX: 12,
        itemPaddingY: 12,
        itemBorderRadius: 8,
        itemGap: 0,
        itemHoverBackground: 'quaternary',
        menuItemLabel: {
          layout: 'inline',
          separator: '',
          gap: 6,
          planName: {
            show: true,
            displayMode: 'text',
            fontSize: 'sm',
            fontWeight: 'medium',
            textColor: 'primary',
            opacity: '100',
            badgeColor: 'brand',
          },
          credits: {
            show: true,
            displayMode: 'text',
            fontSize: 'sm',
            fontWeight: 'normal',
            textColor: 'tertiary',
            opacity: '60',
            badgeColor: 'gray',
          },
        },
        availableTiers: ['tier-100', 'tier-200', 'tier-300', 'tier-400', 'tier-500', 'tier-600'],
        upgradeMode: true,
        showSelectedIndicator: false,
        triggerTypography: {
          label: {
            text: '200 credits',
            show: false,
            fontSize: 'sm',
            fontWeight: 'semibold',
            textColor: 'primary',
          },
          price: {
            prefix: '$',
            show: true,
            fontSize: '3xl',
            fontWeight: 'medium',
            textColor: 'primary',
          },
          priceSuffix: {
            text: 'due today',
            show: true,
            fontSize: 'xs',
            fontWeight: 'normal',
            textColor: 'tertiary',
            opacity: '60',
          },
          subtext: {
            text: 'Pro 2x - 200 credits / mo',
            show: false,
            fontSize: 'xs',
            fontWeight: 'normal',
            textColor: 'tertiary',
            opacity: '60',
          },
          priceRowAlign: 'center',
          priceRowGap: 8,
          rowGap: 4,
        },
        itemTypography: {
          label: {
            fontSize: 'sm',
            fontWeight: 'normal',
            textColor: 'primary',
          },
          price: {
            fontSize: 'sm',
            fontWeight: 'normal',
            textColor: 'tertiary',
            opacity: '100',
          },
        },
      },
      variantB: DEFAULT_VARIANT_B_CONFIG,
    },
  },
]

// ============================================================================
// HELPERS
// ============================================================================

export const getPresetById = (id: string): BiaxialExpandPresetMeta | undefined =>
  BIAXIAL_EXPAND_PRESETS.find((p) => p.id === id)

export const getPresetsByCategory = (category: string): BiaxialExpandPresetMeta[] =>
  BIAXIAL_EXPAND_PRESETS.filter((p) => p.category === category)
