/**
 * Origin Images Comparison - Presets
 */

import type { OriginImagesConfig, OriginImagesPresetMeta } from './types'

export const DEFAULT_CONFIG: OriginImagesConfig = {
  displayMode: 'card',
  showPoster: true,
  showLogo: true,
  showBackdrop: true,
  cardImageType: 'poster',
  width: 72,
  height: 72,
  borderRadius: 16,
  gap: 24,
  columns: 5,
  paddingX: 24,
  paddingY: 24,
  showLabel: true,
  labelPosition: 'bottom',
  labelGap: 8,
  logoBg: true,
  logoBgColor: 'bg-tertiary',
  logoPaddingX: 6,
  logoPaddingY: 4,
  logoShine: 'none',
  logoSquircle: false,
  logoInvert: 0,
  showBackdropBehind: false,
  backdropShine: 'none',
  backdropOpacity: 1,
  labelColor: 'text-secondary',
  labelOpacity: 1,
  labelWeight: 500,
}

export const PRESETS: OriginImagesPresetMeta[] = [
  {
    id: 'app-icon',
    name: 'App Icon',
    description: 'iPhone-style icons with poster and name below',
    data: DEFAULT_CONFIG,
  },
  {
    id: 'app-icon-backdrop',
    name: 'Icon + Backdrop',
    description: 'App icons with cinematic backdrop behind',
    data: {
      ...DEFAULT_CONFIG,
      showBackdropBehind: true,
    },
  },
  {
    id: 'poster-cards',
    name: 'Poster Cards',
    description: 'Tall poster cards like movie posters',
    data: {
      ...DEFAULT_CONFIG,
      width: 80,
      height: 120,
      borderRadius: 10,
      gap: 20,
    },
  },
  {
    id: 'backdrop-cards',
    name: 'Backdrop Cards',
    description: 'Wide cinematic backdrop cards',
    data: {
      ...DEFAULT_CONFIG,
      cardImageType: 'backdrop',
      width: 160,
      height: 90,
      borderRadius: 10,
      gap: 20,
      columns: 4,
    },
  },
  {
    id: 'logo-cards',
    name: 'Logo Cards',
    description: 'Title art logos with name',
    data: {
      ...DEFAULT_CONFIG,
      cardImageType: 'logo',
      width: 72,
      height: 20,
      borderRadius: 7,
      logoBg: true,
      logoBgColor: 'bg-quaternary',
      logoPaddingX: 6,
      logoPaddingY: 6,
      logoShine: 'shine-3',
      logoSquircle: true,
    },
  },
  {
    id: 'logo-backdrop',
    name: 'Logo + Backdrop',
    description: 'Logo over cinematic backdrop',
    data: {
      ...DEFAULT_CONFIG,
      cardImageType: 'logo',
      width: 36,
      height: 20,
      borderRadius: 4,
      labelGap: 4,
      logoBg: false,
      logoBgColor: 'bg-quaternary',
      logoPaddingX: 7,
      logoPaddingY: 6,
      logoShine: 'shine-3',
      logoSquircle: true,
      logoInvert: 0,
      showBackdropBehind: true,
      backdropShine: 'shine-3-shadow-sm',
      backdropOpacity: 0.7,
      labelColor: 'text-tertiary',
      labelOpacity: 0.7,
      labelWeight: 500,
    },
  },
  {
    id: 'compare-all',
    name: 'Compare All',
    description: 'All three types side by side',
    data: {
      ...DEFAULT_CONFIG,
      displayMode: 'comparison',
      cardImageType: 'poster',
      width: 40,
      height: 40,
      borderRadius: 4,
      gap: 16,
    },
  },
  {
    id: 'table-size',
    name: 'Table Size (20px)',
    description: 'Match the 20px size used in stacking-nav-table',
    data: {
      ...DEFAULT_CONFIG,
      displayMode: 'comparison',
      cardImageType: 'poster',
      width: 20,
      height: 20,
      borderRadius: 2,
      gap: 12,
    },
  },
]
