/**
 * Stacking Nav + Table Playground - Presets
 *
 * Playground configuration presets.
 */

import type { PlaygroundConfig } from './types'

export const PRESET_DEFAULT: PlaygroundConfig = {
  dataVariant: 'characters',
  pageBackground: 'secondary_alt',
  pageTopGap: 256,
  pageMaxWidth: 840,
  enableSelection: false,
  showColumnControl: false,
  showCount: true,
  toolbarPaddingTop: 8,
  toolbarPaddingBottom: 16,
  toolbarPaddingLeft: 2,
  toolbarPaddingRight: 0,
  navToCountGap: 12,
  tableOpacity: 100,
  tableMuted: false,
  enableColumnReorder: true,
  borderRadius: 8,
  showOuterBorder: true,
  showRowBorders: false,
  showCellBorders: false,
  outerBorderColor: 'secondary',
  rowBorderColor: 'secondary',
  rowBorderOpacity: 40,
  cellBorderColor: 'secondary',
  cellBorderOpacity: 35,
  badgeStyle: 'default',
  badgeShape: 'squircle',
  badgeNeutral: true,
  originAvatarWidth: 20,
  originAvatarHeight: 20,
  originImageType: 'poster',
  originLogoBg: false,
  originLogoBgColor: 'bg-tertiary',
  originLogoPaddingX: 4,
  originLogoPaddingY: 3,
  originLogoShine: 'none',
  originLogoSquircle: false,
  originLogoInvert: 0,
  sparklineHeight: 24,
  sparklineStrokeWidth: 1.5,
  sparklineShowFill: true,
  sparklineShowDot: true,
  navVariant: 'default',
  showNavDebug: false,
}

export const PRESET_COMPACT: PlaygroundConfig = {
  dataVariant: 'characters',
  pageBackground: 'primary',
  pageTopGap: 48,
  pageMaxWidth: 640,
  enableSelection: false,
  showColumnControl: false,
  showCount: false,
  toolbarPaddingTop: 6,
  toolbarPaddingBottom: 8,
  toolbarPaddingLeft: 8,
  toolbarPaddingRight: 0,
  navToCountGap: 0,
  tableOpacity: 100,
  tableMuted: false,
  enableColumnReorder: false,
  borderRadius: 12,
  showOuterBorder: true,
  showRowBorders: true,
  showCellBorders: false,
  outerBorderColor: 'primary',
  rowBorderColor: 'secondary',
  rowBorderOpacity: 100,
  cellBorderColor: 'tertiary',
  cellBorderOpacity: 100,
  badgeStyle: 'default',
  badgeShape: 'pill',
  badgeNeutral: false,
  originAvatarWidth: 20,
  originAvatarHeight: 20,
  originImageType: 'poster',
  originLogoBg: false,
  originLogoBgColor: 'bg-tertiary',
  originLogoPaddingX: 4,
  originLogoPaddingY: 3,
  originLogoShine: 'none',
  originLogoSquircle: false,
  originLogoInvert: 0,
  sparklineHeight: 20,
  sparklineStrokeWidth: 1,
  sparklineShowFill: false,
  sparklineShowDot: true,
  navVariant: 'default',
  showNavDebug: false,
}

export type PresetId = 'default' | 'compact'

export const PRESETS: Record<PresetId, PlaygroundConfig> = {
  default: PRESET_DEFAULT,
  compact: PRESET_COMPACT,
}
