import type { CoinStackConfig, CoinStackPreset } from './types'

// Default configuration - matches original SVG
export const DEFAULT_CONFIG: CoinStackConfig = {
  size: {
    width: 200,
  },
  bottomTier: {
    faceColor: 'white',
    useGradient: false,
    gradient: {
      enabled: false,
      type: 'linear',
      direction: 'to-bottom',
      startColor: 'gray-100',
      endColor: 'gray-300',
      startOpacity: 100,
      endOpacity: 100,
    },
    strokeColor: 'black',
    strokeWidth: 2,
    shadowColor: 'black',
    shadowOpacity: 100,
  },
  topTier: {
    faceColor: 'white',
    useGradient: false,
    gradient: {
      enabled: false,
      type: 'linear',
      direction: 'to-bottom',
      startColor: 'gray-100',
      endColor: 'gray-300',
      startOpacity: 100,
      endOpacity: 100,
    },
    strokeColor: 'black',
    strokeWidth: 2,
    shadowColor: 'black',
    shadowOpacity: 100,
  },
  effects: {
    dropShadow: 'none',
    dropShadowColor: 'black',
    dropShadowOpacity: 30,
    innerGlow: 'none',
    innerGlowColor: 'white',
    shineOverlay: 'none',
  },
  demo: {
    pageBackground: 'secondary',
    showDebug: false,
  },
}

// Presets
export const PRESETS: CoinStackPreset[] = [
  {
    id: 'default',
    name: 'Classic',
    description: 'Original black/white from SVG',
    config: DEFAULT_CONFIG,
  },
  {
    id: 'gold-metallic',
    name: 'Gold Metallic',
    description: 'Linear gradient gold, warm shadow, strong shine',
    config: {
      ...DEFAULT_CONFIG,
      bottomTier: {
        faceColor: 'gold-500',
        useGradient: true,
        gradient: {
          enabled: true,
          type: 'linear',
          direction: 'to-bottom',
          startColor: 'gold-300',
          endColor: 'gold-600',
          startOpacity: 100,
          endOpacity: 100,
        },
        strokeColor: 'gold-600',
        strokeWidth: 1.5,
        shadowColor: 'gold-600',
        shadowOpacity: 80,
      },
      topTier: {
        faceColor: 'gold-400',
        useGradient: true,
        gradient: {
          enabled: true,
          type: 'linear',
          direction: 'to-bottom',
          startColor: 'gold-300',
          endColor: 'gold-500',
          startOpacity: 100,
          endOpacity: 100,
        },
        strokeColor: 'gold-600',
        strokeWidth: 1.5,
        shadowColor: 'gold-600',
        shadowOpacity: 70,
      },
      effects: {
        dropShadow: 'lg',
        dropShadowColor: 'gold-600',
        dropShadowOpacity: 40,
        innerGlow: 'subtle',
        innerGlowColor: 'gold-300',
        shineOverlay: 'strong',
      },
    },
  },
  {
    id: 'brand-gradient',
    name: 'Brand',
    description: 'Radial gradient with brand tokens',
    config: {
      ...DEFAULT_CONFIG,
      bottomTier: {
        faceColor: 'brand-primary',
        useGradient: true,
        gradient: {
          enabled: true,
          type: 'radial',
          direction: 'to-bottom-right',
          startColor: 'brand-primary',
          endColor: 'brand-secondary',
          startOpacity: 100,
          endOpacity: 100,
        },
        strokeColor: 'brand-secondary',
        strokeWidth: 1,
        shadowColor: 'gray-800',
        shadowOpacity: 90,
      },
      topTier: {
        faceColor: 'brand-primary',
        useGradient: true,
        gradient: {
          enabled: true,
          type: 'radial',
          direction: 'to-bottom-right',
          startColor: 'brand-primary',
          endColor: 'brand-secondary',
          startOpacity: 100,
          endOpacity: 90,
        },
        strokeColor: 'brand-secondary',
        strokeWidth: 1,
        shadowColor: 'gray-700',
        shadowOpacity: 85,
      },
      effects: {
        dropShadow: 'md',
        dropShadowColor: 'brand-primary',
        dropShadowOpacity: 25,
        innerGlow: 'subtle',
        innerGlowColor: 'white',
        shineOverlay: 'subtle',
      },
    },
  },
  {
    id: 'subtle-depth',
    name: 'Subtle Depth',
    description: 'Soft gradients with large drop shadow',
    config: {
      ...DEFAULT_CONFIG,
      bottomTier: {
        faceColor: 'gray-200',
        useGradient: true,
        gradient: {
          enabled: true,
          type: 'linear',
          direction: 'to-bottom',
          startColor: 'gray-100',
          endColor: 'gray-300',
          startOpacity: 100,
          endOpacity: 100,
        },
        strokeColor: 'gray-300',
        strokeWidth: 0.5,
        shadowColor: 'gray-500',
        shadowOpacity: 60,
      },
      topTier: {
        faceColor: 'gray-100',
        useGradient: true,
        gradient: {
          enabled: true,
          type: 'linear',
          direction: 'to-bottom',
          startColor: 'white',
          endColor: 'gray-200',
          startOpacity: 100,
          endOpacity: 100,
        },
        strokeColor: 'gray-300',
        strokeWidth: 0.5,
        shadowColor: 'gray-400',
        shadowOpacity: 50,
      },
      effects: {
        dropShadow: 'xl',
        dropShadowColor: 'black',
        dropShadowOpacity: 15,
        innerGlow: 'subtle',
        innerGlowColor: 'white',
        shineOverlay: 'subtle',
      },
    },
  },
  {
    id: 'arcade-blue-solid',
    name: 'Arcade Blue Solid',
    description: 'Clean solid blue with arcade styling',
    config: {
      ...DEFAULT_CONFIG,
      bottomTier: {
        faceColor: 'sky-300',
        useGradient: false,
        gradient: {
          enabled: false,
          type: 'linear',
          direction: 'to-bottom',
          startColor: 'sky-300',
          endColor: 'white',
          startOpacity: 100,
          endOpacity: 100,
        },
        strokeColor: 'blue-400',
        strokeWidth: 1,
        shadowColor: 'blue-500',
        shadowOpacity: 70,
      },
      topTier: {
        faceColor: 'sky-300',
        useGradient: false,
        gradient: {
          enabled: false,
          type: 'linear',
          direction: 'to-bottom',
          startColor: 'white',
          endColor: 'sky-300',
          startOpacity: 100,
          endOpacity: 100,
        },
        strokeColor: 'blue-400',
        strokeWidth: 1,
        shadowColor: 'blue-400',
        shadowOpacity: 60,
      },
      effects: {
        dropShadow: 'lg',
        dropShadowColor: 'blue-500',
        dropShadowOpacity: 30,
        innerGlow: 'subtle',
        innerGlowColor: 'white',
        shineOverlay: 'medium',
      },
    },
  },
  {
    id: 'arcade-blue',
    name: 'Arcade Blue',
    description: 'Soft blue gradient inspired by arcade aesthetics',
    config: {
      ...DEFAULT_CONFIG,
      bottomTier: {
        faceColor: 'sky-300',
        useGradient: true,
        gradient: {
          enabled: true,
          type: 'linear',
          direction: 'to-bottom',
          startColor: 'sky-300',
          endColor: 'white',
          startOpacity: 100,
          endOpacity: 100,
        },
        strokeColor: 'blue-400',
        strokeWidth: 1,
        shadowColor: 'blue-500',
        shadowOpacity: 70,
      },
      topTier: {
        faceColor: 'sky-300',
        useGradient: true,
        gradient: {
          enabled: true,
          type: 'linear',
          direction: 'to-bottom',
          startColor: 'white',
          endColor: 'sky-300',
          startOpacity: 100,
          endOpacity: 100,
        },
        strokeColor: 'blue-400',
        strokeWidth: 1,
        shadowColor: 'blue-400',
        shadowOpacity: 60,
      },
      effects: {
        dropShadow: 'lg',
        dropShadowColor: 'blue-500',
        dropShadowOpacity: 30,
        innerGlow: 'subtle',
        innerGlowColor: 'white',
        shineOverlay: 'medium',
      },
    },
  },
  {
    id: 'ocean-depth',
    name: 'Ocean Depth',
    description: 'Deep blue tones with cyan highlights',
    config: {
      ...DEFAULT_CONFIG,
      bottomTier: {
        faceColor: 'blue-500',
        useGradient: true,
        gradient: {
          enabled: true,
          type: 'linear',
          direction: 'to-bottom',
          startColor: 'blue-400',
          endColor: 'blue-600',
          startOpacity: 100,
          endOpacity: 100,
        },
        strokeColor: 'blue-600',
        strokeWidth: 1.5,
        shadowColor: 'blue-600',
        shadowOpacity: 85,
      },
      topTier: {
        faceColor: 'cyan-300',
        useGradient: true,
        gradient: {
          enabled: true,
          type: 'linear',
          direction: 'to-bottom',
          startColor: 'cyan-300',
          endColor: 'blue-400',
          startOpacity: 100,
          endOpacity: 100,
        },
        strokeColor: 'blue-500',
        strokeWidth: 1.5,
        shadowColor: 'blue-500',
        shadowOpacity: 75,
      },
      effects: {
        dropShadow: 'lg',
        dropShadowColor: 'blue-600',
        dropShadowOpacity: 35,
        innerGlow: 'medium',
        innerGlowColor: 'cyan-300',
        shineOverlay: 'subtle',
      },
    },
  },
  {
    id: 'frost',
    name: 'Frost',
    description: 'Light icy feel with subtle sky-to-white gradient',
    config: {
      ...DEFAULT_CONFIG,
      bottomTier: {
        faceColor: 'sky-300',
        useGradient: true,
        gradient: {
          enabled: true,
          type: 'linear',
          direction: 'to-bottom',
          startColor: 'white',
          endColor: 'sky-300',
          startOpacity: 100,
          endOpacity: 80,
        },
        strokeColor: 'sky-400',
        strokeWidth: 0.5,
        shadowColor: 'sky-400',
        shadowOpacity: 50,
      },
      topTier: {
        faceColor: 'white',
        useGradient: true,
        gradient: {
          enabled: true,
          type: 'linear',
          direction: 'to-bottom',
          startColor: 'white',
          endColor: 'sky-300',
          startOpacity: 100,
          endOpacity: 60,
        },
        strokeColor: 'sky-300',
        strokeWidth: 0.5,
        shadowColor: 'sky-300',
        shadowOpacity: 40,
      },
      effects: {
        dropShadow: 'xl',
        dropShadowColor: 'sky-400',
        dropShadowOpacity: 20,
        innerGlow: 'subtle',
        innerGlowColor: 'white',
        shineOverlay: 'strong',
      },
    },
  },
  {
    id: 'electric-blue',
    name: 'Electric Blue',
    description: 'Vibrant indigo-to-blue gradient with high energy',
    config: {
      ...DEFAULT_CONFIG,
      bottomTier: {
        faceColor: 'indigo-500',
        useGradient: true,
        gradient: {
          enabled: true,
          type: 'linear',
          direction: 'to-bottom',
          startColor: 'indigo-400',
          endColor: 'indigo-500',
          startOpacity: 100,
          endOpacity: 100,
        },
        strokeColor: 'indigo-500',
        strokeWidth: 1.5,
        shadowColor: 'indigo-500',
        shadowOpacity: 90,
      },
      topTier: {
        faceColor: 'blue-400',
        useGradient: true,
        gradient: {
          enabled: true,
          type: 'linear',
          direction: 'to-bottom',
          startColor: 'blue-300',
          endColor: 'blue-500',
          startOpacity: 100,
          endOpacity: 100,
        },
        strokeColor: 'indigo-500',
        strokeWidth: 1.5,
        shadowColor: 'blue-500',
        shadowOpacity: 80,
      },
      effects: {
        dropShadow: 'lg',
        dropShadowColor: 'indigo-500',
        dropShadowOpacity: 40,
        innerGlow: 'medium',
        innerGlowColor: 'blue-300',
        shineOverlay: 'medium',
      },
    },
  },
  {
    id: 'blue-gold',
    name: 'Blue Gold',
    description: 'Premium blue and gold combination',
    config: {
      ...DEFAULT_CONFIG,
      bottomTier: {
        faceColor: 'gold-500',
        useGradient: true,
        gradient: {
          enabled: true,
          type: 'linear',
          direction: 'to-bottom',
          startColor: 'gold-300',
          endColor: 'gold-600',
          startOpacity: 100,
          endOpacity: 100,
        },
        strokeColor: 'gold-600',
        strokeWidth: 1.5,
        shadowColor: 'gold-600',
        shadowOpacity: 80,
      },
      topTier: {
        faceColor: 'blue-500',
        useGradient: true,
        gradient: {
          enabled: true,
          type: 'linear',
          direction: 'to-bottom',
          startColor: 'blue-300',
          endColor: 'blue-500',
          startOpacity: 100,
          endOpacity: 100,
        },
        strokeColor: 'blue-600',
        strokeWidth: 1.5,
        shadowColor: 'blue-600',
        shadowOpacity: 75,
      },
      effects: {
        dropShadow: 'lg',
        dropShadowColor: 'gold-500',
        dropShadowOpacity: 35,
        innerGlow: 'subtle',
        innerGlowColor: 'gold-300',
        shineOverlay: 'strong',
      },
    },
  },
  {
    id: 'aurora',
    name: 'Aurora',
    description: 'Blue to violet to cyan aurora borealis effect',
    config: {
      ...DEFAULT_CONFIG,
      bottomTier: {
        faceColor: 'blue-400',
        useGradient: true,
        gradient: {
          enabled: true,
          type: 'linear',
          direction: 'to-bottom',
          startColor: 'blue-400',
          endColor: 'cyan-300',
          startOpacity: 100,
          endOpacity: 100,
        },
        strokeColor: 'cyan-400',
        strokeWidth: 1,
        shadowColor: 'cyan-400',
        shadowOpacity: 70,
      },
      topTier: {
        faceColor: 'indigo-500',
        useGradient: true,
        gradient: {
          enabled: true,
          type: 'linear',
          direction: 'to-bottom',
          startColor: 'indigo-400',
          endColor: 'violet-400',
          startOpacity: 100,
          endOpacity: 100,
        },
        strokeColor: 'violet-500',
        strokeWidth: 1,
        shadowColor: 'violet-500',
        shadowOpacity: 75,
      },
      effects: {
        dropShadow: 'lg',
        dropShadowColor: 'violet-500',
        dropShadowOpacity: 30,
        innerGlow: 'medium',
        innerGlowColor: 'cyan-300',
        shineOverlay: 'medium',
      },
    },
  },
]

// Get preset by ID
export function getPresetById(id: string): CoinStackPreset | undefined {
  return PRESETS.find((preset) => preset.id === id)
}
