import type { PlaygroundConfig, ConfigPreset } from './types'

// =============================================================================
// FULL CONFIG PRESETS
// =============================================================================

/** Default preset — tuned spring animation with instant child entry */
const PRESET_DEFAULT: Omit<PlaygroundConfig, 'configPreset' | 'navVariant'> = {
  animationType: 'spring',
  springStiffness: 650,
  springDamping: 38,
  springMass: 0.9,
  springPreset: 'custom',
  tweenDuration: 300,
  tweenEase: 'expoOut',
  promotionDuration: 200,
  promotionScale: 1,
  childStagger: 25,
  entryDirection: 'custom',
  entryOffsetX: 6,
  entryOffsetY: 10,
  childEntryDelay: 0,
  childEntryScale: 1,
  childEntryOpacity: 0,
  entryFromParent: true,
  entryInstant: true,
  exitScale: 1,
  exitUseCustomTiming: true,
  exitDuration: 0,
  exitEase: 'expoOut',
  exitDelay: 0,
  collapseLayoutDuration: 300,
  skipLeafAnimation: true,
  syncChildEntryToPromotion: false,
  promotionChildOffset: 0,
  demotionEntryDelay: 0,
  demotionStagger: 15,
  demotionEntryOpacity: 0,
  demotionEntryScale: 0.75,
  buttonSize: 'md',
  buttonRoundness: 'pill',
  expandedVariant: 'shine',
  childVariant: 'tab',
  anchoredVariant: 'secondary',
  selectedLeafVariant: 'tab',
  reentryVariant: 'tab',
  demotingVariant: 'reentry',
  peekOffset: 8,
  anchoredOpacity: 1,
  gap: 'md',
  showNumbers: false,
  showDebug: false,
  pageBackground: 'primary',
  showLevelAll: true,
  levelAllLabel: 'All',
  levelAllActiveVariant: 'tab',
  levelAllInactiveVariant: 'tab',
  hoverDelay: 0,
  slowMoEnabled: false,
  showPhaseIndicator: false,
  containerWidth: 640,
  navMinHeight: 70,
  showContainerBounds: false,
  containerOverflow: 'visible',
  showOverflowGradient: false,
  gradientWidth: 80,
  containerPaddingTop: 0,
  containerPaddingRight: 0,
  containerPaddingBottom: 0,
  containerPaddingLeft: 0,
  showContentGrid: false,
  navAlignment: 'left',
  debugAlignment: 'left',
  debugSpacing: 40,
  debugOffsetX: 4,
}

export const CONFIG_PRESETS: Record<
  ConfigPreset,
  Omit<PlaygroundConfig, 'configPreset' | 'navVariant'> | null
> = {
  default: PRESET_DEFAULT,
  custom: null,
}

export const DEFAULT_PLAYGROUND_CONFIG: PlaygroundConfig = {
  configPreset: 'default',
  ...PRESET_DEFAULT,
  navVariant: 'orders',
}
