import type { DeckSlideCardPresetMeta, DeckSlideCardConfig } from './types'

/**
 * Deck Slide Card Presets
 *
 * Preset categories:
 * - default: Standard starting point (current production style)
 * - minimal: Clean, understated
 * - elevated: Premium, with depth effects
 * - brand: Uses brand colors and effects
 * - print: Optimized for PDF export
 * - custom: User-defined variations
 */

export const DEFAULT_DECK_SLIDE_CARD_CONFIG: DeckSlideCardConfig = {
  outer: {
    background: 'gradient',
    gradientFrom: 'tertiary',
    gradientTo: 'quaternary',
    gradientDirection: 'to-br',
    shine: 'shine-1',
    shineIntensity: '',
    shadow: 'none',
    depth: 'none',
    corner: 'squircle',
    borderRadius: 16,
    padding: 32,
    border: false,
    borderColor: 'primary',
    borderWidth: 1,
  },
  content: {
    type: 'stat',
    statValue: '$250B → $480B',
    statLabel: 'Creator economy growth by 2027',
    statSubtext: '',
    showArrow: true,
    titleColor: 'primary',
    labelColor: 'secondary',
    subtextColor: 'quaternary',
    titleSize: 'display-2xl',
    labelSize: 'lg',
    subtextSize: 'sm',
  },
  layout: {
    width: 'auto',
    minWidth: 320,
    height: 'auto',
    minHeight: 180,
    aspectRatio: 'auto',
  },
  export: {
    printOptimized: false,
    forceLight: false,
    viewportScaling: false,
  },
}

export const DECK_SLIDE_CARD_PRESETS: DeckSlideCardPresetMeta[] = [
  {
    id: 'default',
    name: 'Default (Production)',
    category: 'default',
    description: 'Current production slide card style',
    data: DEFAULT_DECK_SLIDE_CARD_CONFIG,
  },
  {
    id: 'minimal',
    name: 'Minimal',
    category: 'minimal',
    description: 'Clean, no effects',
    data: {
      outer: {
        background: 'secondary',
        shine: 'none',
        shineIntensity: '',
        shadow: 'none',
        depth: 'none',
        corner: 'round',
        borderRadius: 8,
        padding: 24,
        border: true,
        borderColor: 'secondary',
        borderWidth: 1,
      },
      content: {
        type: 'stat',
        statValue: '92%',
        statLabel: 'Customer satisfaction',
        statSubtext: 'Based on 10,000+ reviews',
        showArrow: false,
        titleColor: 'primary',
        labelColor: 'secondary',
        subtextColor: 'tertiary',
        titleSize: 'display-xl',
        labelSize: 'md',
        subtextSize: 'sm',
      },
      layout: {
        width: 'auto',
        minWidth: 280,
        height: 'auto',
        minHeight: 160,
        aspectRatio: 'auto',
      },
      export: {
        printOptimized: false,
        forceLight: false,
        viewportScaling: false,
      },
    },
  },
  {
    id: 'elevated',
    name: 'Elevated',
    category: 'elevated',
    description: 'Premium card with depth',
    data: {
      outer: {
        background: 'gradient',
        gradientFrom: 'secondary',
        gradientTo: 'tertiary',
        gradientDirection: 'to-br',
        shine: 'shine-2',
        shineIntensity: '-subtle',
        shadow: 'lg',
        depth: 'depth-gradient-2',
        corner: 'squircle',
        borderRadius: 24,
        padding: 40,
        border: false,
        borderColor: 'primary',
        borderWidth: 1,
      },
      content: {
        type: 'stat',
        statValue: '10x',
        statLabel: 'Faster processing',
        statSubtext: 'Compared to traditional methods',
        showArrow: false,
        titleColor: 'primary',
        labelColor: 'secondary',
        subtextColor: 'quaternary',
        titleSize: 'display-2xl',
        labelSize: 'lg',
        subtextSize: 'sm',
      },
      layout: {
        width: 'auto',
        minWidth: 340,
        height: 'auto',
        minHeight: 200,
        aspectRatio: 'auto',
      },
      export: {
        printOptimized: false,
        forceLight: false,
        viewportScaling: false,
      },
    },
  },
  {
    id: 'brand-solid',
    name: 'Brand Solid',
    category: 'brand',
    description: 'Solid brand background',
    data: {
      outer: {
        background: 'brand-solid',
        shine: 'shine-brand',
        shineIntensity: '',
        shadow: 'md',
        depth: 'none',
        corner: 'squircle',
        borderRadius: 20,
        padding: 32,
        border: false,
        borderColor: 'primary',
        borderWidth: 1,
      },
      content: {
        type: 'stat',
        statValue: '$1.2M',
        statLabel: 'Revenue generated',
        statSubtext: 'Q4 2024',
        showArrow: false,
        titleColor: 'primary',
        labelColor: 'secondary',
        subtextColor: 'tertiary',
        titleSize: 'display-xl',
        labelSize: 'lg',
        subtextSize: 'sm',
      },
      layout: {
        width: 'auto',
        minWidth: 300,
        height: 'auto',
        minHeight: 180,
        aspectRatio: 'auto',
      },
      export: {
        printOptimized: false,
        forceLight: false,
        viewportScaling: false,
      },
    },
  },
  {
    id: 'print-optimized',
    name: 'Print Optimized',
    category: 'print',
    description: 'Optimized for PDF export with subtle effects',
    data: {
      outer: {
        background: 'gradient',
        gradientFrom: 'white',
        gradientTo: 'secondary',
        gradientDirection: 'to-b',
        shine: 'shine-3',
        shineIntensity: '-subtle',
        shadow: 'none',
        depth: 'none',
        corner: 'squircle',
        borderRadius: 16,
        padding: 32,
        border: true,
        borderColor: 'tertiary',
        borderWidth: 1,
      },
      content: {
        type: 'stat',
        statValue: '150K+',
        statLabel: 'Active users',
        statSubtext: 'Growing 20% MoM',
        showArrow: false,
        titleColor: 'primary',
        labelColor: 'secondary',
        subtextColor: 'tertiary',
        titleSize: 'display-xl',
        labelSize: 'lg',
        subtextSize: 'md',
      },
      layout: {
        width: 'auto',
        minWidth: 320,
        height: 'auto',
        minHeight: 180,
        aspectRatio: 'auto',
      },
      export: {
        printOptimized: true,
        forceLight: true,
        viewportScaling: true,
      },
    },
  },
  {
    id: 'high-contrast',
    name: 'High Contrast',
    category: 'custom',
    description: 'High contrast for accessibility',
    data: {
      outer: {
        background: 'primary',
        shine: 'shine-1',
        shineIntensity: '-intense',
        shadow: 'sm',
        depth: 'none',
        corner: 'round',
        borderRadius: 12,
        padding: 28,
        border: true,
        borderColor: 'primary',
        borderWidth: 2,
      },
      content: {
        type: 'stat',
        statValue: '99.99%',
        statLabel: 'Uptime SLA',
        statSubtext: 'Enterprise grade reliability',
        showArrow: false,
        titleColor: 'primary',
        labelColor: 'primary',
        subtextColor: 'secondary',
        titleSize: 'display-lg',
        labelSize: 'lg',
        subtextSize: 'md',
      },
      layout: {
        width: 'auto',
        minWidth: 300,
        height: 'auto',
        minHeight: 170,
        aspectRatio: 'auto',
      },
      export: {
        printOptimized: false,
        forceLight: false,
        viewportScaling: false,
      },
    },
  },
  {
    id: 'glass-effect',
    name: 'Glass Effect',
    category: 'custom',
    description: 'Frosted glass appearance',
    data: {
      outer: {
        background: 'gradient',
        gradientFrom: 'tertiary',
        gradientTo: 'quaternary',
        gradientDirection: 'to-br',
        shine: 'shine-3',
        shineIntensity: '',
        shadow: 'md',
        depth: 'depth-gradient-1',
        corner: 'squircle',
        borderRadius: 20,
        padding: 36,
        border: true,
        borderColor: 'secondary',
        borderWidth: 1,
      },
      content: {
        type: 'stat',
        statValue: '5 stars',
        statLabel: 'Average rating',
        statSubtext: '2,500+ reviews',
        showArrow: false,
        titleColor: 'primary',
        labelColor: 'secondary',
        subtextColor: 'tertiary',
        titleSize: 'display-lg',
        labelSize: 'md',
        subtextSize: 'sm',
      },
      layout: {
        width: 'auto',
        minWidth: 280,
        height: 'auto',
        minHeight: 160,
        aspectRatio: 'auto',
      },
      export: {
        printOptimized: false,
        forceLight: false,
        viewportScaling: false,
      },
    },
  },
]

export const getPresetById = (id: string): DeckSlideCardPresetMeta | undefined =>
  DECK_SLIDE_CARD_PRESETS.find((p) => p.id === id)

export const getPresetsByCategory = (category: string): DeckSlideCardPresetMeta[] =>
  DECK_SLIDE_CARD_PRESETS.filter((p) => p.category === category)