/**
 * Pricing Select Menu - Presets Index
 */

export {
  // Combined preset
  UPGRADE_FLOW_PRESET,
  // Dimensions
  UPGRADE_FLOW_DIMENSIONS,
  // Animation
  UPGRADE_FLOW_ANIMATION,
  // Appearance
  UPGRADE_FLOW_APPEARANCE,
  // Bottom slot
  UPGRADE_FLOW_BOTTOM_SLOT,
  // Dropdown icon
  UPGRADE_FLOW_DROPDOWN_ICON,
  // Trigger
  UPGRADE_FLOW_TRIGGER_PADDING,
  UPGRADE_FLOW_TRIGGER_TYPOGRAPHY,
  UPGRADE_FLOW_SYNCED_SUBTEXT,
  // Options list
  UPGRADE_FLOW_OPTIONS_LIST,
  UPGRADE_FLOW_ITEM_TYPOGRAPHY,
  UPGRADE_FLOW_MENU_ITEM_LABEL,
  // Variant B
  UPGRADE_FLOW_VARIANT_B_TRIGGER,
  UPGRADE_FLOW_VARIANT_B_BOTTOM,
  UPGRADE_FLOW_VARIANT_B_TRANSITION,
} from './upgrade-flow'
