/**
 * Stacking Nav + Table Playground - Presets
 *
 * Playground configuration presets.
 */

import type { PlaygroundConfig } from './types'

export const PRESET_DEFAULT: PlaygroundConfig = {
  dataVariant: 'characters',
  pageBackground: 'secondary_alt',
  pageTopGap: 256,
  pageMaxWidth: 920,
  enableSelection: false,
  showColumnControl: false,
  showCount: true,
  toolbarPaddingTop: 8,
  toolbarPaddingBottom: 16,
  toolbarPaddingLeft: 2,
  toolbarPaddingRight: 0,
  navToCountGap: 12,
  tableOpacity: 100,
  tableMuted: false,
  enableColumnReorder: true,
  borderRadius: 8,
  showOuterBorder: true,
  showRowBorders: false,
  showCellBorders: false,
  outerBorderColor: 'secondary',
  rowBorderColor: 'secondary',
  rowBorderOpacity: 40,
  cellBorderColor: 'secondary',
  cellBorderOpacity: 35,
  badgeStyle: 'default',
  badgeShape: 'squircle',
  badgeNeutral: true,
  originAvatarWidth: 30,
  originAvatarHeight: 22,
  originImageType: 'none',
  originShowLabel: true,
  originLabelOpacity: 0.55,
  originLogoBg: false,
  originLogoBgColor: 'bg-gray-950',
  originLogoPaddingX: 6,
  originLogoPaddingY: 3,
  originLogoShine: 'shine-3-shadow-sm',
  originLogoSquircle: false,
  originLogoInvert: 0,
  // Logo outline
  originLogoOutline: false,
  originLogoOutlineColor: 'auto',
  originLogoOutlineSize: 0.5,
  originLogoOutlineOpacity: 0.45,
  originLogoOutlineIntensity: 2,
  // Backdrop behind
  originShowBackdrop: false,
  originBackdropPaddingX: 6,
  originBackdropPaddingY: 2,
  originBackdropShine: 'shine-2-shadow-sm',
  originBackdropOpacity: 0.65,
  originBackdropRadius: 4,
  chartType: 'bar',
  sparklineHeight: 24,
  sparklineStrokeWidth: 1.5,
  sparklineShowFill: true,
  sparklineShowDot: true,
  sparklineShowBaseline: true,
  sparklineBaselineWidth: 0.5,
  sparklineBaselineOpacity: 0.25,
  // Bar Chart
  barGap: 1.5,
  barRadius: 0,
  barOpacity: 45,
  barColorMode: 'status',
  barChartColor: '1',
  barPositiveColor: 'chart-1',
  barNegativeColor: 'error',
  barShowTips: false,
  barTipSize: 1.5,
  barTipColorMode: 'status',
  barTipChartColor: '1',
  barTipPositiveColor: 'chart-1',
  barTipNegativeColor: 'error',
  barShowTrendLine: true,
  barTrendLineWidth: 0.5,
  barTrendLineOpacity: 0.65,
  barTrendLineColorMode: 'chart',
  barTrendLineChartColor: '4',
  barTrendLineStatusColor: 'neutral-dark',
  // Baseline
  barBaselineColorMode: 'status',
  barBaselineChartColor: '1',
  barBaselineStatusColor: 'warning',
  navVariant: 'default',
  showNavDebug: false,
}

export const PRESET_COMPACT: PlaygroundConfig = {
  dataVariant: 'characters',
  pageBackground: 'primary',
  pageTopGap: 48,
  pageMaxWidth: 640,
  enableSelection: false,
  showColumnControl: false,
  showCount: false,
  toolbarPaddingTop: 6,
  toolbarPaddingBottom: 8,
  toolbarPaddingLeft: 8,
  toolbarPaddingRight: 0,
  navToCountGap: 0,
  tableOpacity: 100,
  tableMuted: false,
  enableColumnReorder: false,
  borderRadius: 12,
  showOuterBorder: true,
  showRowBorders: true,
  showCellBorders: false,
  outerBorderColor: 'primary',
  rowBorderColor: 'secondary',
  rowBorderOpacity: 100,
  cellBorderColor: 'tertiary',
  cellBorderOpacity: 100,
  badgeStyle: 'default',
  badgeShape: 'pill',
  badgeNeutral: false,
  originAvatarWidth: 20,
  originAvatarHeight: 20,
  originImageType: 'poster',
  originShowLabel: true,
  originLabelOpacity: 1,
  originLogoBg: false,
  originLogoBgColor: 'bg-tertiary',
  originLogoPaddingX: 4,
  originLogoPaddingY: 3,
  originLogoShine: 'none',
  originLogoSquircle: false,
  originLogoInvert: 0,
  // Logo outline
  originLogoOutline: false,
  originLogoOutlineColor: 'auto',
  originLogoOutlineSize: 0.5,
  originLogoOutlineOpacity: 0.45,
  originLogoOutlineIntensity: 2,
  // Backdrop behind
  originShowBackdrop: false,
  originBackdropPaddingX: 8,
  originBackdropPaddingY: 6,
  originBackdropShine: 'shine-2-shadow-sm',
  originBackdropOpacity: 0.85,
  originBackdropRadius: 4,
  chartType: 'line',
  sparklineHeight: 20,
  sparklineStrokeWidth: 1,
  sparklineShowFill: false,
  sparklineShowDot: true,
  sparklineShowBaseline: true,
  sparklineBaselineWidth: 0.5,
  sparklineBaselineOpacity: 0.2,
  // Bar Chart
  barGap: 1,
  barRadius: 1,
  barOpacity: 40,
  barColorMode: 'neutral',
  barChartColor: '1',
  barPositiveColor: 'success',
  barNegativeColor: 'error',
  barShowTips: false,
  barTipSize: 2,
  barTipColorMode: 'status',
  barTipChartColor: '1',
  barTipPositiveColor: 'success',
  barTipNegativeColor: 'error',
  barShowTrendLine: false,
  barTrendLineWidth: 1,
  barTrendLineOpacity: 0.6,
  barTrendLineColorMode: 'neutral',
  barTrendLineChartColor: '1',
  barTrendLineStatusColor: 'neutral-dark',
  // Baseline
  barBaselineColorMode: 'neutral',
  barBaselineChartColor: '1',
  barBaselineStatusColor: 'neutral',
  navVariant: 'default',
  showNavDebug: false,
}

export type PresetId = 'default' | 'compact'

export const PRESETS: Record<PresetId, PlaygroundConfig> = {
  default: PRESET_DEFAULT,
  compact: PRESET_COMPACT,
}
