/**
 * Pricing Modal Control Panel Configuration
 *
 * Builds the panel config for UnifiedControlPanel.
 */

import type { PanelConfig, Section } from '@/components/ui/patterns/control-panel'
import type { PricingPlaygroundConfig, PricingPresetMeta } from '../config/types'
import {
  CORNER_SHAPE_OPTIONS,
  BACKGROUND_OPTIONS,
  SHINE_OPTIONS,
  DEPTH_OPTIONS,
  SHADOW_OPTIONS,
  BORDER_COLOR_OPTIONS,
  TEXT_COLOR_OPTIONS,
  TITLE_SIZE_OPTIONS,
  TEXT_SIZE_OPTIONS,
  TEXT_ALIGN_OPTIONS,
  WEIGHT_OPTIONS,
  BUTTON_VARIANT_OPTIONS,
  BUTTON_SIZE_OPTIONS,
  CLOSE_BUTTON_POSITION_OPTIONS,
  CLOSE_BUTTON_SIZE_OPTIONS,
  ICON_STROKE_WIDTH_OPTIONS,
  BACKGROUND_MODE_OPTIONS,
  CLOSE_BUTTON_RADIUS_OPTIONS,
  CLOSE_BUTTON_BG_COLOR_OPTIONS,
  ANIMATION_PRESET_OPTIONS,
  PAGE_BACKGROUND_OPTIONS,
  CONTENT_TYPE_OPTIONS,
  PRO_CARD_TEXT_STYLE_OPTIONS,
  PRO_CARD_BACKGROUND_OPTIONS,
  GLOW_COLOR_OPTIONS,
  PRO_CARD_FONT_WEIGHT_OPTIONS,
  SEPARATOR_POSITION_OPTIONS,
  COIN_STACK_PRESET_OPTIONS,
  COIN_STACK_ALIGNMENT_OPTIONS,
  COIN_STACK_SIZE_MODE_OPTIONS,
  ASSET_BACKGROUND_OPTIONS,
  COIN_STACK_DEPTH_OPTIONS,
  PRICING_SELECT_BACKGROUND_OPTIONS,
  PRICING_SELECT_BORDER_RADIUS_OPTIONS,
  PRICING_SELECT_EASING_OPTIONS,
  PRICING_SELECT_GRADIENT_OPTIONS,
  PRICING_SELECT_GRADIENT_COLOR_OPTIONS,
  PRICING_SELECT_BORDER_COLOR_OPTIONS,
  CONTENT_A_HEADER_SIZE_OPTIONS,
  CHECKLIST_ITEM_GAP_OPTIONS,
  CHECKLIST_TEXT_SIZE_OPTIONS,
  CHECKLIST_TEXT_WEIGHT_OPTIONS,
  CHECKLIST_COLOR_OPTIONS,
  CHECKLIST_ICON_SIZE_OPTIONS,
  CHECKLIST_ICON_WEIGHT_OPTIONS,
  CHECKLIST_ICON_COLOR_OPTIONS,
  RADIAL_FLARE_COLOR_OPTIONS,
  NOISE_BLEND_MODE_OPTIONS,
  BACKDROP_COLOR_OPTIONS,
} from '../config/options'

// ============================================================================
// Panel Builder
// ============================================================================

export function buildPricingPanelConfig(
  config: PricingPlaygroundConfig,
  presets: PricingPresetMeta[],
  activePresetId: string | null
): PanelConfig {
  return {
    sections: [
      buildContainerSection(config),
      buildRadialFlareSection(config),
      buildDecorationsSection(config),
      buildAssetSection(config),
      buildCloseButtonSection(config),
      buildHeaderSection(config),
      buildSeparatorSection(config),
      buildContentASection(config),
      buildContentBSection(config),
      buildButtonSection(config),
      buildProCardSection(config),
      buildChecklistSection(config),
      buildPricingSelectSection(config),
      buildAnimationSection(config),
      buildFlowsSection(config),
      buildDemoSection(config),
      buildBackdropSection(config),
    ],
    presetConfig: {
      presets: presets.map((p) => ({
        id: p.id,
        name: p.name,
        data: p.data,
      })),
      activePresetId,
      showCopyButton: true,
    },
    showReset: true,
  }
}

// ============================================================================
// Section Builders
// ============================================================================

function buildContainerSection(config: PricingPlaygroundConfig): Section {
  return {
    id: 'container',
    label: 'Container',
    title: 'Container',
    groups: [
      {
        title: 'Dimensions',
        controls: [
          {
            id: 'container.width',
            type: 'slider',
            label: 'Width',
            value: config.container.width,
            min: 280,
            max: 560,
            step: 20,
            formatLabel: (v: number) => `${v}px`,
          },
          {
            id: 'container.height',
            type: 'slider',
            label: 'Height',
            value: config.container.height,
            min: 300,
            max: 700,
            step: 20,
            formatLabel: (v: number) => `${v}px`,
          },
        ],
      },
      {
        title: 'Spacing',
        controls: [
          {
            id: 'container.padding',
            type: 'slider',
            label: 'Padding',
            value: config.container.padding,
            min: 12,
            max: 48,
            step: 4,
            formatLabel: (v: number) => `${v}px`,
          },
          {
            id: 'container.gap',
            type: 'slider',
            label: 'Gap',
            value: config.container.gap,
            min: 4,
            max: 32,
            step: 4,
            formatLabel: (v: number) => `${v}px`,
          },
        ],
      },
      {
        title: 'Corners',
        controls: [
          {
            id: 'container.borderRadius',
            type: 'slider',
            label: 'Radius',
            value: config.container.borderRadius,
            min: 0,
            max: 32,
            step: 4,
            formatLabel: (v: number) => `${v}px`,
          },
          {
            id: 'container.cornerShape',
            type: 'select',
            label: 'Shape',
            value: config.container.cornerShape,
            options: [...CORNER_SHAPE_OPTIONS],
          },
        ],
      },
      {
        title: 'Surface',
        controls: [
          {
            id: 'container.background',
            type: 'color-select',
            label: 'Background',
            value: config.container.background,
            options: [...BACKGROUND_OPTIONS],
          },
          {
            id: 'container.shine',
            type: 'select',
            label: 'Shine',
            value: config.container.shine,
            options: [...SHINE_OPTIONS],
          },
          {
            id: 'container.depth',
            type: 'select',
            label: 'Depth',
            value: config.container.depth,
            options: [...DEPTH_OPTIONS],
          },
          {
            id: 'container.shadow',
            type: 'select',
            label: 'Shadow',
            value: config.container.shadow,
            options: [...SHADOW_OPTIONS],
          },
        ],
      },
      {
        title: 'Border',
        defaultCollapsed: true,
        controls: [
          {
            id: 'container.borderWidth',
            type: 'slider',
            label: 'Width',
            value: config.container.borderWidth,
            min: 0,
            max: 4,
            step: 1,
            formatLabel: (v: number) => `${v}px`,
          },
          {
            id: 'container.borderColor',
            type: 'color-select',
            label: 'Color',
            value: config.container.borderColor,
            options: [...BORDER_COLOR_OPTIONS],
          },
        ],
      },
    ],
  }
}

function buildRadialFlareSection(config: PricingPlaygroundConfig): Section {
  return {
    id: 'radialFlare',
    label: 'Flare',
    title: 'Radial Flare',
    groups: [
      {
        controls: [
          {
            id: 'radialFlare.enabled',
            type: 'toggle',
            label: 'Enable Radial Flare',
            value: config.radialFlare.enabled,
          },
        ],
      },
      {
        title: 'Flare 1 (Base Layer)',
        controls: [
          {
            id: 'radialFlare.flare1.enabled',
            type: 'toggle',
            label: 'Enable',
            value: config.radialFlare.flare1.enabled,
            disabled: !config.radialFlare.enabled,
          },
          {
            id: 'radialFlare.flare1.color',
            type: 'color-select',
            label: 'Color',
            value: config.radialFlare.flare1.color,
            options: [...RADIAL_FLARE_COLOR_OPTIONS],
            disabled: !config.radialFlare.enabled || !config.radialFlare.flare1.enabled,
          },
          {
            id: 'radialFlare.flare1.opacity',
            type: 'slider',
            label: 'Opacity',
            value: config.radialFlare.flare1.opacity,
            min: 0,
            max: 50,
            step: 1,
            formatLabel: (v: number) => `${v}%`,
            disabled: !config.radialFlare.enabled || !config.radialFlare.flare1.enabled,
          },
          {
            id: 'radialFlare.flare1.size',
            type: 'slider',
            label: 'Size',
            value: config.radialFlare.flare1.size,
            min: 40,
            max: 400,
            step: 10,
            formatLabel: (v: number) => `${v}px`,
            disabled: !config.radialFlare.enabled || !config.radialFlare.flare1.enabled,
          },
          {
            id: 'radialFlare.flare1.blur',
            type: 'slider',
            label: 'Blur',
            value: config.radialFlare.flare1.blur,
            min: 0,
            max: 120,
            step: 5,
            formatLabel: (v: number) => `${v}px`,
            disabled: !config.radialFlare.enabled || !config.radialFlare.flare1.enabled,
          },
          {
            id: 'radialFlare.flare1.offsetX',
            type: 'slider',
            label: 'X Offset',
            value: config.radialFlare.flare1.offsetX,
            min: -100,
            max: 200,
            step: 5,
            formatLabel: (v: number) => `${v}px`,
            disabled: !config.radialFlare.enabled || !config.radialFlare.flare1.enabled,
          },
          {
            id: 'radialFlare.flare1.offsetY',
            type: 'slider',
            label: 'Y Offset',
            value: config.radialFlare.flare1.offsetY,
            min: -100,
            max: 200,
            step: 5,
            formatLabel: (v: number) => `${v}px`,
            disabled: !config.radialFlare.enabled || !config.radialFlare.flare1.enabled,
          },
        ],
      },
      {
        title: 'Flare 2 (Brand Layer)',
        defaultCollapsed: true,
        controls: [
          {
            id: 'radialFlare.flare2.enabled',
            type: 'toggle',
            label: 'Enable',
            value: config.radialFlare.flare2.enabled,
            disabled: !config.radialFlare.enabled,
          },
          {
            id: 'radialFlare.flare2.color',
            type: 'color-select',
            label: 'Color',
            value: config.radialFlare.flare2.color,
            options: [...RADIAL_FLARE_COLOR_OPTIONS],
            disabled: !config.radialFlare.enabled || !config.radialFlare.flare2.enabled,
          },
          {
            id: 'radialFlare.flare2.opacity',
            type: 'slider',
            label: 'Opacity',
            value: config.radialFlare.flare2.opacity,
            min: 0,
            max: 50,
            step: 1,
            formatLabel: (v: number) => `${v}%`,
            disabled: !config.radialFlare.enabled || !config.radialFlare.flare2.enabled,
          },
          {
            id: 'radialFlare.flare2.size',
            type: 'slider',
            label: 'Size',
            value: config.radialFlare.flare2.size,
            min: 40,
            max: 400,
            step: 10,
            formatLabel: (v: number) => `${v}px`,
            disabled: !config.radialFlare.enabled || !config.radialFlare.flare2.enabled,
          },
          {
            id: 'radialFlare.flare2.blur',
            type: 'slider',
            label: 'Blur',
            value: config.radialFlare.flare2.blur,
            min: 0,
            max: 120,
            step: 5,
            formatLabel: (v: number) => `${v}px`,
            disabled: !config.radialFlare.enabled || !config.radialFlare.flare2.enabled,
          },
          {
            id: 'radialFlare.flare2.offsetX',
            type: 'slider',
            label: 'X Offset',
            value: config.radialFlare.flare2.offsetX,
            min: -100,
            max: 200,
            step: 5,
            formatLabel: (v: number) => `${v}px`,
            disabled: !config.radialFlare.enabled || !config.radialFlare.flare2.enabled,
          },
          {
            id: 'radialFlare.flare2.offsetY',
            type: 'slider',
            label: 'Y Offset',
            value: config.radialFlare.flare2.offsetY,
            min: -100,
            max: 200,
            step: 5,
            formatLabel: (v: number) => `${v}px`,
            disabled: !config.radialFlare.enabled || !config.radialFlare.flare2.enabled,
          },
        ],
      },
      {
        title: 'Flare 3 (Accent Layer)',
        defaultCollapsed: true,
        controls: [
          {
            id: 'radialFlare.flare3.enabled',
            type: 'toggle',
            label: 'Enable',
            value: config.radialFlare.flare3.enabled,
            disabled: !config.radialFlare.enabled,
          },
          {
            id: 'radialFlare.flare3.color',
            type: 'color-select',
            label: 'Color',
            value: config.radialFlare.flare3.color,
            options: [...RADIAL_FLARE_COLOR_OPTIONS],
            disabled: !config.radialFlare.enabled || !config.radialFlare.flare3.enabled,
          },
          {
            id: 'radialFlare.flare3.opacity',
            type: 'slider',
            label: 'Opacity',
            value: config.radialFlare.flare3.opacity,
            min: 0,
            max: 50,
            step: 1,
            formatLabel: (v: number) => `${v}%`,
            disabled: !config.radialFlare.enabled || !config.radialFlare.flare3.enabled,
          },
          {
            id: 'radialFlare.flare3.size',
            type: 'slider',
            label: 'Size',
            value: config.radialFlare.flare3.size,
            min: 40,
            max: 400,
            step: 10,
            formatLabel: (v: number) => `${v}px`,
            disabled: !config.radialFlare.enabled || !config.radialFlare.flare3.enabled,
          },
          {
            id: 'radialFlare.flare3.blur',
            type: 'slider',
            label: 'Blur',
            value: config.radialFlare.flare3.blur,
            min: 0,
            max: 120,
            step: 5,
            formatLabel: (v: number) => `${v}px`,
            disabled: !config.radialFlare.enabled || !config.radialFlare.flare3.enabled,
          },
          {
            id: 'radialFlare.flare3.offsetX',
            type: 'slider',
            label: 'X Offset',
            value: config.radialFlare.flare3.offsetX,
            min: -100,
            max: 200,
            step: 5,
            formatLabel: (v: number) => `${v}px`,
            disabled: !config.radialFlare.enabled || !config.radialFlare.flare3.enabled,
          },
          {
            id: 'radialFlare.flare3.offsetY',
            type: 'slider',
            label: 'Y Offset',
            value: config.radialFlare.flare3.offsetY,
            min: -100,
            max: 200,
            step: 5,
            formatLabel: (v: number) => `${v}px`,
            disabled: !config.radialFlare.enabled || !config.radialFlare.flare3.enabled,
          },
        ],
      },
    ],
  }
}

function buildDecorationsSection(config: PricingPlaygroundConfig): Section {
  return {
    id: 'decorations',
    label: 'Decor',
    title: 'Decorations',
    groups: [
      {
        title: 'Noise Texture',
        controls: [
          {
            id: 'decorations.noise.enabled',
            type: 'toggle',
            label: 'Enable Noise',
            value: config.decorations.noise.enabled,
          },
          {
            id: 'decorations.noise.opacity',
            type: 'slider',
            label: 'Opacity',
            value: config.decorations.noise.opacity,
            min: 0,
            max: 30,
            step: 1,
            formatLabel: (v: number) => `${v}%`,
            disabled: !config.decorations.noise.enabled,
          },
          {
            id: 'decorations.noise.scale',
            type: 'slider',
            label: 'Scale',
            value: config.decorations.noise.scale,
            min: 0.5,
            max: 3,
            step: 0.25,
            formatLabel: (v: number) => `${v}x`,
            disabled: !config.decorations.noise.enabled,
          },
          {
            id: 'decorations.noise.radialFade',
            type: 'slider',
            label: 'Radial Fade',
            value: config.decorations.noise.radialFade,
            min: 0,
            max: 100,
            step: 5,
            formatLabel: (v: number) => `${v}%`,
            disabled: !config.decorations.noise.enabled,
          },
          {
            id: 'decorations.noise.blendMode',
            type: 'select',
            label: 'Blend Mode',
            value: config.decorations.noise.blendMode,
            options: [...NOISE_BLEND_MODE_OPTIONS],
            disabled: !config.decorations.noise.enabled,
          },
        ],
      },
      {
        title: 'Sparkles',
        defaultCollapsed: true,
        controls: [
          {
            id: 'decorations.sparkles.enabled',
            type: 'toggle',
            label: 'Enable Sparkles',
            value: config.decorations.sparkles.enabled,
          },
          {
            id: 'decorations.sparkles.count',
            type: 'slider',
            label: 'Count',
            value: config.decorations.sparkles.count,
            min: 3,
            max: 12,
            step: 1,
            disabled: !config.decorations.sparkles.enabled,
          },
          {
            id: 'decorations.sparkles.size',
            type: 'slider',
            label: 'Size',
            value: config.decorations.sparkles.size,
            min: 4,
            max: 20,
            step: 1,
            formatLabel: (v: number) => `${v}px`,
            disabled: !config.decorations.sparkles.enabled,
          },
          {
            id: 'decorations.sparkles.sizeVariation',
            type: 'slider',
            label: 'Size Variation',
            value: config.decorations.sparkles.sizeVariation,
            min: 0,
            max: 100,
            step: 10,
            formatLabel: (v: number) => `${v}%`,
            disabled: !config.decorations.sparkles.enabled,
          },
          {
            id: 'decorations.sparkles.opacity',
            type: 'slider',
            label: 'Opacity',
            value: config.decorations.sparkles.opacity,
            min: 0,
            max: 100,
            step: 5,
            formatLabel: (v: number) => `${v}%`,
            disabled: !config.decorations.sparkles.enabled,
          },
          {
            id: 'decorations.sparkles.spread',
            type: 'slider',
            label: 'Spread',
            value: config.decorations.sparkles.spread,
            min: 40,
            max: 250,
            step: 10,
            formatLabel: (v: number) => `${v}px`,
            disabled: !config.decorations.sparkles.enabled,
          },
          {
            id: 'decorations.sparkles.radialFade',
            type: 'slider',
            label: 'Radial Fade',
            value: config.decorations.sparkles.radialFade,
            min: 0,
            max: 100,
            step: 5,
            formatLabel: (v: number) => `${v}%`,
            disabled: !config.decorations.sparkles.enabled,
          },
          {
            id: 'decorations.sparkles.color',
            type: 'color-select',
            label: 'Color',
            value: config.decorations.sparkles.color,
            options: [...RADIAL_FLARE_COLOR_OPTIONS],
            disabled: !config.decorations.sparkles.enabled,
          },
        ],
      },
      {
        title: 'Rings',
        defaultCollapsed: true,
        controls: [
          {
            id: 'decorations.rings.enabled',
            type: 'toggle',
            label: 'Enable Rings',
            value: config.decorations.rings.enabled,
          },
          {
            id: 'decorations.rings.count',
            type: 'slider',
            label: 'Count',
            value: config.decorations.rings.count,
            min: 1,
            max: 5,
            step: 1,
            disabled: !config.decorations.rings.enabled,
          },
          {
            id: 'decorations.rings.startRadius',
            type: 'slider',
            label: 'Start Radius',
            value: config.decorations.rings.startRadius,
            min: 20,
            max: 150,
            step: 10,
            formatLabel: (v: number) => `${v}px`,
            disabled: !config.decorations.rings.enabled,
          },
          {
            id: 'decorations.rings.gap',
            type: 'slider',
            label: 'Gap',
            value: config.decorations.rings.gap,
            min: 10,
            max: 60,
            step: 5,
            formatLabel: (v: number) => `${v}px`,
            disabled: !config.decorations.rings.enabled,
          },
          {
            id: 'decorations.rings.strokeWidth',
            type: 'slider',
            label: 'Stroke Width',
            value: config.decorations.rings.strokeWidth,
            min: 0.5,
            max: 4,
            step: 0.5,
            formatLabel: (v: number) => `${v}px`,
            disabled: !config.decorations.rings.enabled,
          },
          {
            id: 'decorations.rings.arcAngle',
            type: 'slider',
            label: 'Arc Angle',
            value: config.decorations.rings.arcAngle,
            min: 45,
            max: 180,
            step: 15,
            formatLabel: (v: number) => `${v}°`,
            disabled: !config.decorations.rings.enabled,
          },
          {
            id: 'decorations.rings.opacity',
            type: 'slider',
            label: 'Opacity',
            value: config.decorations.rings.opacity,
            min: 0,
            max: 50,
            step: 5,
            formatLabel: (v: number) => `${v}%`,
            disabled: !config.decorations.rings.enabled,
          },
          {
            id: 'decorations.rings.radialFade',
            type: 'slider',
            label: 'Radial Fade',
            value: config.decorations.rings.radialFade,
            min: 0,
            max: 100,
            step: 5,
            formatLabel: (v: number) => `${v}%`,
            disabled: !config.decorations.rings.enabled,
          },
          {
            id: 'decorations.rings.color',
            type: 'color-select',
            label: 'Color',
            value: config.decorations.rings.color,
            options: [...RADIAL_FLARE_COLOR_OPTIONS],
            disabled: !config.decorations.rings.enabled,
          },
        ],
      },
    ],
  }
}

function buildAssetSection(config: PricingPlaygroundConfig): Section {
  return {
    id: 'asset',
    label: 'Asset',
    title: 'Asset',
    groups: [
      {
        controls: [
          {
            id: 'asset.show',
            type: 'toggle',
            label: 'Show Asset Section',
            value: config.asset.show,
          },
          {
            id: 'asset.height',
            type: 'slider',
            label: 'Height',
            value: config.asset.height,
            min: 32,
            max: 160,
            step: 8,
            formatLabel: (v: number) => `${v}px`,
            disabled: !config.asset.show,
          },
          {
            id: 'asset.xOffset',
            type: 'slider',
            label: 'X Offset',
            value: config.asset.xOffset,
            min: -64,
            max: 64,
            step: 2,
            formatLabel: (v: number) => `${v}px`,
            disabled: !config.asset.show,
          },
          {
            id: 'asset.background',
            type: 'color-select',
            label: 'Section Background',
            value: config.asset.background,
            options: [...ASSET_BACKGROUND_OPTIONS],
            disabled: !config.asset.show,
          },
        ],
      },
      {
        title: 'Coin Stack',
        controls: [
          {
            id: 'asset.coinStack.enabled',
            type: 'toggle',
            label: 'Enable Coin Stack',
            value: config.asset.coinStack.enabled,
            disabled: !config.asset.show,
          },
          {
            id: 'asset.coinStack.presetId',
            type: 'select',
            label: 'Preset',
            value: config.asset.coinStack.presetId,
            options: [...COIN_STACK_PRESET_OPTIONS],
            disabled: !config.asset.show || !config.asset.coinStack.enabled,
          },
          {
            id: 'asset.coinStack.width',
            type: 'slider',
            label: 'Size',
            value: config.asset.coinStack.width,
            min: 50,
            max: 160,
            step: 10,
            formatLabel: (v: number) => `${v}px`,
            disabled: !config.asset.show || !config.asset.coinStack.enabled,
          },
          {
            id: 'asset.coinStack.alignment',
            type: 'select',
            label: 'Alignment',
            value: config.asset.coinStack.alignment,
            options: [...COIN_STACK_ALIGNMENT_OPTIONS],
            disabled: !config.asset.show || !config.asset.coinStack.enabled,
          },
        ],
      },
      {
        title: 'Coin Stack Background',
        defaultCollapsed: true,
        controls: [
          {
            id: 'asset.coinStack.showBackground',
            type: 'toggle',
            label: 'Show Background',
            value: config.asset.coinStack.showBackground,
            disabled: !config.asset.show || !config.asset.coinStack.enabled,
          },
          {
            id: 'asset.coinStack.background',
            type: 'color-select',
            label: 'Color',
            value: config.asset.coinStack.background,
            options: [...BACKGROUND_OPTIONS],
            disabled: !config.asset.show || !config.asset.coinStack.enabled || !config.asset.coinStack.showBackground,
          },
          {
            id: 'asset.coinStack.sizeMode',
            type: 'select',
            label: 'Size Mode',
            value: config.asset.coinStack.sizeMode,
            options: [...COIN_STACK_SIZE_MODE_OPTIONS],
            disabled: !config.asset.show || !config.asset.coinStack.enabled || !config.asset.coinStack.showBackground,
          },
          {
            id: 'asset.coinStack.backgroundPadding',
            type: 'slider',
            label: 'Padding',
            value: config.asset.coinStack.backgroundPadding,
            min: 0,
            max: 24,
            step: 2,
            formatLabel: (v: number) => `${v}px`,
            disabled: !config.asset.show || !config.asset.coinStack.enabled || !config.asset.coinStack.showBackground || config.asset.coinStack.sizeMode !== 'padding',
          },
          {
            id: 'asset.coinStack.fixedSize',
            type: 'slider',
            label: 'Square Size',
            value: config.asset.coinStack.fixedSize,
            min: 48,
            max: 160,
            step: 4,
            formatLabel: (v: number) => `${v}px`,
            disabled: !config.asset.show || !config.asset.coinStack.enabled || !config.asset.coinStack.showBackground || config.asset.coinStack.sizeMode !== 'fixed',
          },
          {
            id: 'asset.coinStack.backgroundRadius',
            type: 'select',
            label: 'Radius',
            value: config.asset.coinStack.backgroundRadius === 'full' ? 'full' : String(config.asset.coinStack.backgroundRadius),
            options: [
              { label: 'Full (Pill)', value: 'full' },
              { label: '24px', value: '24' },
              { label: '20px', value: '20' },
              { label: '16px', value: '16' },
              { label: '12px', value: '12' },
              { label: '8px', value: '8' },
              { label: '4px', value: '4' },
              { label: '0px', value: '0' },
            ],
            disabled: !config.asset.show || !config.asset.coinStack.enabled || !config.asset.coinStack.showBackground,
          },
          {
            id: 'asset.coinStack.cornerShape',
            type: 'select',
            label: 'Corner Shape',
            value: config.asset.coinStack.cornerShape,
            options: [...CORNER_SHAPE_OPTIONS],
            disabled: !config.asset.show || !config.asset.coinStack.enabled || !config.asset.coinStack.showBackground,
          },
          {
            id: 'asset.coinStack.shine',
            type: 'select',
            label: 'Shine',
            value: config.asset.coinStack.shine,
            options: [...SHINE_OPTIONS],
            disabled: !config.asset.show || !config.asset.coinStack.enabled || !config.asset.coinStack.showBackground,
          },
          {
            id: 'asset.coinStack.depth',
            type: 'select',
            label: 'Depth',
            value: config.asset.coinStack.depth,
            options: [...COIN_STACK_DEPTH_OPTIONS],
            disabled: !config.asset.show || !config.asset.coinStack.enabled || !config.asset.coinStack.showBackground,
          },
          {
            id: 'asset.coinStack.shadow',
            type: 'select',
            label: 'Shadow',
            value: config.asset.coinStack.shadow,
            options: [...SHADOW_OPTIONS],
            disabled: !config.asset.show || !config.asset.coinStack.enabled || !config.asset.coinStack.showBackground,
          },
        ],
      },
    ],
  }
}

function buildCloseButtonSection(config: PricingPlaygroundConfig): Section {
  return {
    id: 'closeButton',
    label: 'Close',
    title: 'Close Button',
    groups: [
      {
        controls: [
          {
            id: 'closeButton.show',
            type: 'toggle',
            label: 'Show Close Button',
            value: config.closeButton.show,
          },
        ],
      },
      {
        title: 'Position',
        controls: [
          {
            id: 'closeButton.position',
            type: 'select',
            label: 'Position',
            value: config.closeButton.position,
            options: [...CLOSE_BUTTON_POSITION_OPTIONS],
            disabled: !config.closeButton.show,
          },
          {
            id: 'closeButton.offset',
            type: 'slider',
            label: 'Offset',
            value: config.closeButton.offset,
            min: 8,
            max: 24,
            step: 4,
            formatLabel: (v: number) => `${v}px`,
            disabled: !config.closeButton.show,
          },
          {
            id: 'closeButton.size',
            type: 'select',
            label: 'Size',
            value: config.closeButton.size,
            options: [...CLOSE_BUTTON_SIZE_OPTIONS],
            disabled: !config.closeButton.show,
          },
        ],
      },
      {
        title: 'Icon',
        defaultCollapsed: true,
        controls: [
          {
            id: 'closeButton.iconStrokeWidth',
            type: 'select',
            label: 'Stroke Width',
            value: String(config.closeButton.iconStrokeWidth),
            options: [...ICON_STROKE_WIDTH_OPTIONS],
            disabled: !config.closeButton.show,
          },
          {
            id: 'closeButton.iconColor',
            type: 'color-select',
            label: 'Icon Color',
            value: config.closeButton.iconColor,
            options: [...TEXT_COLOR_OPTIONS],
            disabled: !config.closeButton.show,
          },
        ],
      },
      {
        title: 'Background',
        defaultCollapsed: true,
        controls: [
          {
            id: 'closeButton.backgroundMode',
            type: 'select',
            label: 'Mode',
            value: config.closeButton.backgroundMode,
            options: [...BACKGROUND_MODE_OPTIONS],
            disabled: !config.closeButton.show,
          },
          {
            id: 'closeButton.backgroundColor',
            type: 'color-select',
            label: 'Color',
            value: config.closeButton.backgroundColor,
            options: [...CLOSE_BUTTON_BG_COLOR_OPTIONS],
            disabled: !config.closeButton.show,
          },
          {
            id: 'closeButton.backgroundOpacity',
            type: 'slider',
            label: 'Opacity',
            value: config.closeButton.backgroundOpacity,
            min: 0,
            max: 100,
            step: 10,
            formatLabel: (v: number) => `${v}%`,
            disabled: !config.closeButton.show,
          },
          {
            id: 'closeButton.backgroundRadius',
            type: 'select',
            label: 'Radius',
            value: config.closeButton.backgroundRadius,
            options: [...CLOSE_BUTTON_RADIUS_OPTIONS],
            disabled: !config.closeButton.show,
          },
        ],
      },
    ],
  }
}

function buildHeaderSection(config: PricingPlaygroundConfig): Section {
  return {
    id: 'header',
    label: 'Header',
    title: 'Header',
    groups: [
      {
        title: 'Position',
        controls: [
          {
            id: 'header.topOffset',
            type: 'slider',
            label: 'Top Offset',
            value: config.header.topOffset,
            min: -24,
            max: 24,
            step: 2,
            formatLabel: (v: number) => `${v}px`,
          },
          {
            id: 'header.textAlign',
            type: 'select',
            label: 'Text Align',
            value: config.header.textAlign,
            options: [...TEXT_ALIGN_OPTIONS],
          },
        ],
      },
      {
        title: 'Title',
        controls: [
          {
            id: 'header.title',
            type: 'text',
            label: 'Title Text',
            value: config.header.title,
          },
          {
            id: 'header.titleColor',
            type: 'color-select',
            label: 'Color',
            value: config.header.titleColor,
            options: [...TEXT_COLOR_OPTIONS],
          },
          {
            id: 'header.titleSize',
            type: 'select',
            label: 'Size',
            value: config.header.titleSize,
            options: [...TITLE_SIZE_OPTIONS],
          },
          {
            id: 'header.titleWeight',
            type: 'select',
            label: 'Weight',
            value: config.header.titleWeight,
            options: [...WEIGHT_OPTIONS],
          },
        ],
      },
      {
        title: 'Subheader',
        controls: [
          {
            id: 'header.showSubheader',
            type: 'toggle',
            label: 'Show Subheader',
            value: config.header.showSubheader,
          },
          {
            id: 'header.subheader',
            type: 'text',
            label: 'Subheader Text',
            value: config.header.subheader,
            disabled: !config.header.showSubheader,
          },
          {
            id: 'header.subheaderColor',
            type: 'color-select',
            label: 'Color',
            value: config.header.subheaderColor,
            options: [...TEXT_COLOR_OPTIONS],
            disabled: !config.header.showSubheader,
          },
          {
            id: 'header.subheaderSize',
            type: 'select',
            label: 'Size',
            value: config.header.subheaderSize,
            options: [...TEXT_SIZE_OPTIONS],
            disabled: !config.header.showSubheader,
          },
          {
            id: 'header.subheaderWeight',
            type: 'select',
            label: 'Weight',
            value: config.header.subheaderWeight,
            options: [...WEIGHT_OPTIONS],
            disabled: !config.header.showSubheader,
          },
          {
            id: 'header.gap',
            type: 'slider',
            label: 'Gap',
            value: config.header.gap,
            min: 0,
            max: 24,
            step: 2,
            formatLabel: (v: number) => `${v}px`,
            disabled: !config.header.showSubheader,
          },
        ],
      },
    ],
  }
}

function buildSeparatorSection(config: PricingPlaygroundConfig): Section {
  return {
    id: 'separator',
    label: 'Separator',
    title: 'Line Separator',
    groups: [
      {
        controls: [
          {
            id: 'separator.show',
            type: 'toggle',
            label: 'Show Separator',
            value: config.separator.show,
          },
          {
            id: 'separator.position',
            type: 'select',
            label: 'Position',
            value: config.separator.position,
            options: [...SEPARATOR_POSITION_OPTIONS],
            disabled: !config.separator.show,
          },
        ],
      },
      {
        title: 'Style',
        controls: [
          {
            id: 'separator.thickness',
            type: 'slider',
            label: 'Thickness',
            value: config.separator.thickness,
            min: 1,
            max: 4,
            step: 1,
            formatLabel: (v: number) => `${v}px`,
            disabled: !config.separator.show,
          },
          {
            id: 'separator.color',
            type: 'color-select',
            label: 'Color',
            value: config.separator.color,
            options: [...BORDER_COLOR_OPTIONS],
            disabled: !config.separator.show,
          },
        ],
      },
      {
        title: 'Inset',
        controls: [
          {
            id: 'separator.fullWidth',
            type: 'toggle',
            label: 'Full Width',
            value: config.separator.fullWidth,
            disabled: !config.separator.show,
          },
          {
            id: 'separator.insetAmount',
            type: 'slider',
            label: 'Inset Amount',
            value: config.separator.insetAmount,
            min: 0,
            max: 32,
            step: 4,
            formatLabel: (v: number) => `${v}px`,
            disabled: !config.separator.show || config.separator.fullWidth,
          },
        ],
      },
    ],
  }
}

function buildContentASection(config: PricingPlaygroundConfig): Section {
  return {
    id: 'contentA',
    label: 'Content A',
    title: 'Content A',
    groups: [
      {
        controls: [
          {
            id: 'contentA.show',
            type: 'toggle',
            label: 'Show Content A',
            value: config.contentA.show,
          },
          {
            id: 'contentA.type',
            type: 'select',
            label: 'Type',
            value: config.contentA.type,
            options: [...CONTENT_TYPE_OPTIONS],
            disabled: !config.contentA.show,
          },
        ],
      },
      {
        title: 'Layout',
        controls: [
          {
            id: 'contentA.height',
            type: 'slider',
            label: 'Height',
            value: config.contentA.height,
            min: 16,
            max: 200,
            step: 8,
            formatLabel: (v: number) => `${v}px`,
            disabled: !config.contentA.show,
          },
          ...(config.contentA.type === 'wireframe'
            ? [
                {
                  id: 'contentA.lineCount',
                  type: 'slider' as const,
                  label: 'Lines',
                  value: config.contentA.lineCount,
                  min: 1,
                  max: 6,
                  step: 1,
                  disabled: !config.contentA.show,
                },
                {
                  id: 'contentA.lineGap',
                  type: 'slider' as const,
                  label: 'Line Gap',
                  value: config.contentA.lineGap,
                  min: 4,
                  max: 16,
                  step: 2,
                  formatLabel: (v: number) => `${v}px`,
                  disabled: !config.contentA.show,
                },
              ]
            : []),
        ],
      },
      ...(config.contentA.type === 'wireframe'
        ? [
            {
              title: 'Typography',
              defaultCollapsed: true,
              controls: [
                {
                  id: 'contentA.textColor',
                  type: 'color-select' as const,
                  label: 'Color',
                  value: config.contentA.textColor,
                  options: [...TEXT_COLOR_OPTIONS],
                  disabled: !config.contentA.show,
                },
                {
                  id: 'contentA.textSize',
                  type: 'select' as const,
                  label: 'Size',
                  value: config.contentA.textSize,
                  options: [...TEXT_SIZE_OPTIONS],
                  disabled: !config.contentA.show,
                },
                {
                  id: 'contentA.textWeight',
                  type: 'select' as const,
                  label: 'Weight',
                  value: config.contentA.textWeight,
                  options: [...WEIGHT_OPTIONS],
                  disabled: !config.contentA.show,
                },
              ],
            },
          ]
        : []),
    ],
  }
}

function buildContentBSection(config: PricingPlaygroundConfig): Section {
  return {
    id: 'contentB',
    label: 'Content B',
    title: 'Content B',
    groups: [
      {
        controls: [
          {
            id: 'contentB.show',
            type: 'toggle',
            label: 'Show Content B',
            value: config.contentB.show,
          },
          {
            id: 'contentB.fill',
            type: 'toggle',
            label: 'Fill Remaining Space',
            value: config.contentB.fill,
            disabled: !config.contentB.show,
          },
          {
            id: 'contentB.type',
            type: 'select',
            label: 'Type',
            value: config.contentB.type,
            options: [...CONTENT_TYPE_OPTIONS],
            disabled: !config.contentB.show,
          },
        ],
      },
      {
        title: 'Layout',
        controls: [
          {
            id: 'contentB.height',
            type: 'slider',
            label: 'Height',
            value: config.contentB.height,
            min: 16,
            max: 300,
            step: 8,
            formatLabel: (v: number) => `${v}px`,
            disabled: !config.contentB.show || config.contentB.fill,
          },
          ...(config.contentB.type === 'wireframe'
            ? [
                {
                  id: 'contentB.lineCount',
                  type: 'slider' as const,
                  label: 'Lines',
                  value: config.contentB.lineCount,
                  min: 1,
                  max: 6,
                  step: 1,
                  disabled: !config.contentB.show,
                },
                {
                  id: 'contentB.lineGap',
                  type: 'slider' as const,
                  label: 'Line Gap',
                  value: config.contentB.lineGap,
                  min: 4,
                  max: 16,
                  step: 2,
                  formatLabel: (v: number) => `${v}px`,
                  disabled: !config.contentB.show,
                },
              ]
            : []),
        ],
      },
      ...(config.contentB.type === 'wireframe'
        ? [
            {
              title: 'Typography',
              defaultCollapsed: true,
              controls: [
                {
                  id: 'contentB.textColor',
                  type: 'color-select' as const,
                  label: 'Color',
                  value: config.contentB.textColor,
                  options: [...TEXT_COLOR_OPTIONS],
                  disabled: !config.contentB.show,
                },
                {
                  id: 'contentB.textSize',
                  type: 'select' as const,
                  label: 'Size',
                  value: config.contentB.textSize,
                  options: [...TEXT_SIZE_OPTIONS],
                  disabled: !config.contentB.show,
                },
                {
                  id: 'contentB.textWeight',
                  type: 'select' as const,
                  label: 'Weight',
                  value: config.contentB.textWeight,
                  options: [...WEIGHT_OPTIONS],
                  disabled: !config.contentB.show,
                },
              ],
            },
          ]
        : []),
      ...(config.contentB.type === 'checklist'
        ? [
            {
              title: 'Checklist Layout',
              controls: [
                {
                  id: 'contentB.checklistLayout.maxWidth',
                  type: 'slider' as const,
                  label: 'Max Width',
                  value: config.contentB.checklistLayout?.maxWidth ?? 0,
                  min: 0,
                  max: 400,
                  step: 20,
                  formatLabel: (v: number) => v === 0 ? 'None' : `${v}px`,
                  disabled: !config.contentB.show,
                },
                {
                  id: 'contentB.checklistLayout.centered',
                  type: 'toggle' as const,
                  label: 'Center Content',
                  value: config.contentB.checklistLayout?.centered ?? false,
                  disabled: !config.contentB.show || (config.contentB.checklistLayout?.maxWidth ?? 0) === 0,
                },
                {
                  id: 'contentB.checklistLayout.noWrap',
                  type: 'toggle' as const,
                  label: 'No Text Wrap',
                  value: config.contentB.checklistLayout?.noWrap ?? false,
                  disabled: !config.contentB.show,
                },
                {
                  id: 'contentB.checklistLayout.overflow',
                  type: 'toggle' as const,
                  label: 'Allow Overflow',
                  value: config.contentB.checklistLayout?.overflow ?? false,
                  disabled: !config.contentB.show,
                },
              ],
            },
          ]
        : []),
    ],
  }
}

function buildButtonSection(config: PricingPlaygroundConfig): Section {
  return {
    id: 'button',
    label: 'Button',
    title: 'Button',
    groups: [
      {
        controls: [
          {
            id: 'button.label',
            type: 'text',
            label: 'Label',
            value: config.button.label,
          },
          {
            id: 'button.variant',
            type: 'select',
            label: 'Variant',
            value: config.button.variant,
            options: [...BUTTON_VARIANT_OPTIONS],
          },
          {
            id: 'button.size',
            type: 'select',
            label: 'Size',
            value: config.button.size,
            options: [...BUTTON_SIZE_OPTIONS],
          },
          {
            id: 'button.cornerSquircle',
            type: 'toggle',
            label: 'Corner Squircle',
            value: config.button.cornerSquircle,
          },
        ],
      },
    ],
  }
}

function buildProCardSection(config: PricingPlaygroundConfig): Section {
  return {
    id: 'proCard',
    label: 'Pro Card',
    title: 'Pro Card',
    groups: [
      {
        title: 'Content',
        controls: [
          {
            id: 'proCard.title',
            type: 'text',
            label: 'Title',
            value: config.proCard.title,
          },
          {
            id: 'proCard.multiplier',
            type: 'slider',
            label: 'Multiplier',
            value: config.proCard.multiplier,
            min: 1,
            max: 10,
            step: 1,
            formatLabel: (v: number) => `${v}x`,
          },
        ],
      },
      {
        title: 'Typography',
        controls: [
          {
            id: 'proCard.text.fontSize',
            type: 'slider',
            label: 'Font Size',
            value: config.proCard.text.fontSize === 'auto' ? 36 : config.proCard.text.fontSize,
            min: 16,
            max: 72,
            step: 2,
            formatLabel: (v: number) => `${v}px`,
          },
          {
            id: 'proCard.text.fontWeight',
            type: 'select',
            label: 'Weight',
            value: config.proCard.text.fontWeight,
            options: [...PRO_CARD_FONT_WEIGHT_OPTIONS],
          },
        ],
      },
      {
        title: 'Colors',
        controls: [
          {
            id: 'proCard.text.titleGradient',
            type: 'select',
            label: 'Title Style',
            value: config.proCard.text.titleGradient,
            options: [...PRO_CARD_TEXT_STYLE_OPTIONS],
          },
          {
            id: 'proCard.text.multiplierGradient',
            type: 'select',
            label: 'Multiplier Style',
            value: config.proCard.text.multiplierGradient,
            options: [...PRO_CARD_TEXT_STYLE_OPTIONS],
          },
        ],
      },
      {
        title: 'Container',
        defaultCollapsed: true,
        controls: [
          {
            id: 'proCard.container.background',
            type: 'color-select',
            label: 'Background',
            value: config.proCard.container.background,
            options: [...PRO_CARD_BACKGROUND_OPTIONS],
          },
          {
            id: 'proCard.container.shine',
            type: 'select',
            label: 'Shine',
            value: config.proCard.container.shine,
            options: [...SHINE_OPTIONS],
          },
          {
            id: 'proCard.container.borderRadius',
            type: 'slider',
            label: 'Radius',
            value: config.proCard.container.borderRadius,
            min: 0,
            max: 24,
            step: 4,
            formatLabel: (v: number) => `${v}px`,
          },
          {
            id: 'proCard.container.padding',
            type: 'slider',
            label: 'Padding',
            value: config.proCard.container.padding,
            min: 0,
            max: 32,
            step: 4,
            formatLabel: (v: number) => `${v}px`,
          },
        ],
      },
      {
        title: 'Glow',
        defaultCollapsed: true,
        controls: [
          {
            id: 'proCard.glow.enabled',
            type: 'toggle',
            label: 'Enable Glow',
            value: config.proCard.glow.enabled,
          },
          {
            id: 'proCard.glow.color',
            type: 'color-select',
            label: 'Color',
            value: config.proCard.glow.color,
            options: [...GLOW_COLOR_OPTIONS],
            disabled: !config.proCard.glow.enabled,
          },
          {
            id: 'proCard.glow.blur',
            type: 'slider',
            label: 'Blur',
            value: config.proCard.glow.blur,
            min: 8,
            max: 64,
            step: 4,
            formatLabel: (v: number) => `${v}px`,
            disabled: !config.proCard.glow.enabled,
          },
          {
            id: 'proCard.glow.opacity',
            type: 'slider',
            label: 'Opacity',
            value: config.proCard.glow.opacity,
            min: 0,
            max: 100,
            step: 5,
            formatLabel: (v: number) => `${v}%`,
            disabled: !config.proCard.glow.enabled,
          },
        ],
      },
    ],
  }
}

function buildChecklistSection(config: PricingPlaygroundConfig): Section {
  return {
    id: 'checklist',
    label: 'Checklist',
    title: 'Checklist',
    groups: [
      {
        title: 'Layout',
        controls: [
          {
            id: 'checklist.itemGap',
            type: 'select',
            label: 'Item Gap',
            value: config.checklist.itemGap,
            options: [...CHECKLIST_ITEM_GAP_OPTIONS],
          },
        ],
      },
      {
        title: 'Text Style',
        controls: [
          {
            id: 'checklist.textStyle.size',
            type: 'select',
            label: 'Size',
            value: config.checklist.textStyle.size,
            options: [...CHECKLIST_TEXT_SIZE_OPTIONS],
          },
          {
            id: 'checklist.textStyle.weight',
            type: 'select',
            label: 'Weight',
            value: config.checklist.textStyle.weight,
            options: [...CHECKLIST_TEXT_WEIGHT_OPTIONS],
          },
          {
            id: 'checklist.textStyle.color',
            type: 'color-select',
            label: 'Color',
            value: config.checklist.textStyle.color,
            options: [...CHECKLIST_COLOR_OPTIONS],
          },
          {
            id: 'checklist.textStyle.opacity',
            type: 'slider',
            label: 'Opacity',
            value: config.checklist.textStyle.opacity,
            min: 0,
            max: 100,
            step: 10,
            formatLabel: (v: number) => `${v}%`,
          },
        ],
      },
      {
        title: 'Icon Style',
        controls: [
          {
            id: 'checklist.iconStyle.size',
            type: 'select',
            label: 'Size',
            value: config.checklist.iconStyle.size,
            options: [...CHECKLIST_ICON_SIZE_OPTIONS],
          },
          {
            id: 'checklist.iconStyle.weight',
            type: 'select',
            label: 'Weight',
            value: config.checklist.iconStyle.weight,
            options: [...CHECKLIST_ICON_WEIGHT_OPTIONS],
          },
          {
            id: 'checklist.iconStyle.color',
            type: 'color-select',
            label: 'Color',
            value: config.checklist.iconStyle.color,
            options: [...CHECKLIST_ICON_COLOR_OPTIONS],
          },
          {
            id: 'checklist.iconStyle.opacity',
            type: 'slider',
            label: 'Opacity',
            value: config.checklist.iconStyle.opacity,
            min: 0,
            max: 100,
            step: 10,
            formatLabel: (v: number) => `${v}%`,
          },
        ],
      },
      {
        title: 'Date Style',
        defaultCollapsed: true,
        controls: [
          {
            id: 'checklist.dateStyle.size',
            type: 'select',
            label: 'Size',
            value: config.checklist.dateStyle.size,
            options: [...CHECKLIST_TEXT_SIZE_OPTIONS],
          },
          {
            id: 'checklist.dateStyle.weight',
            type: 'select',
            label: 'Weight',
            value: config.checklist.dateStyle.weight,
            options: [...CHECKLIST_TEXT_WEIGHT_OPTIONS],
          },
          {
            id: 'checklist.dateStyle.color',
            type: 'color-select',
            label: 'Color',
            value: config.checklist.dateStyle.color,
            options: [...CHECKLIST_COLOR_OPTIONS],
          },
          {
            id: 'checklist.dateStyle.opacity',
            type: 'slider',
            label: 'Opacity',
            value: config.checklist.dateStyle.opacity,
            min: 0,
            max: 100,
            step: 10,
            formatLabel: (v: number) => `${v}%`,
          },
        ],
      },
    ],
  }
}

function buildPricingSelectSection(config: PricingPlaygroundConfig): Section {
  return {
    id: 'pricingSelect',
    label: 'Pricing Select',
    title: 'Pricing Select Menu',
    groups: [
      {
        title: 'Appearance',
        controls: [
          {
            id: 'pricingSelect.appearance.background',
            type: 'color-select',
            label: 'Background',
            value: config.pricingSelect.appearance.background,
            options: [...PRICING_SELECT_BACKGROUND_OPTIONS],
          },
          {
            id: 'pricingSelect.appearance.shine',
            type: 'select',
            label: 'Shine',
            value: config.pricingSelect.appearance.shine,
            options: [...SHINE_OPTIONS],
          },
          {
            id: 'pricingSelect.appearance.shadow',
            type: 'select',
            label: 'Shadow',
            value: config.pricingSelect.appearance.shadow,
            options: [...SHADOW_OPTIONS],
          },
          {
            id: 'pricingSelect.appearance.borderRadius',
            type: 'select',
            label: 'Border Radius',
            value: config.pricingSelect.appearance.borderRadius,
            options: [...PRICING_SELECT_BORDER_RADIUS_OPTIONS],
          },
          {
            id: 'pricingSelect.appearance.squircle',
            type: 'toggle',
            label: 'Squircle Corners',
            value: config.pricingSelect.appearance.squircle,
          },
        ],
      },
      {
        title: 'Depth Effect',
        defaultCollapsed: true,
        controls: [
          {
            id: 'pricingSelect.appearance.gradient',
            type: 'select',
            label: 'Gradient',
            value: config.pricingSelect.appearance.gradient,
            options: [...PRICING_SELECT_GRADIENT_OPTIONS],
          },
          {
            id: 'pricingSelect.appearance.gradientColor',
            type: 'color-select',
            label: 'Gradient Color',
            value: config.pricingSelect.appearance.gradientColor,
            options: [...PRICING_SELECT_GRADIENT_COLOR_OPTIONS],
            disabled: config.pricingSelect.appearance.gradient === 'none',
          },
        ],
      },
      {
        title: 'Animation',
        controls: [
          {
            id: 'pricingSelect.animation.duration',
            type: 'slider',
            label: 'Expand Duration',
            value: config.pricingSelect.animation.duration,
            min: 100,
            max: 600,
            step: 25,
            formatLabel: (v: number) => `${v}ms`,
          },
          {
            id: 'pricingSelect.animation.collapseDuration',
            type: 'slider',
            label: 'Collapse Duration',
            value: config.pricingSelect.animation.collapseDuration,
            min: 50,
            max: 400,
            step: 25,
            formatLabel: (v: number) => `${v}ms`,
          },
          {
            id: 'pricingSelect.animation.easing',
            type: 'select',
            label: 'Easing',
            value: config.pricingSelect.animation.easing,
            options: [...PRICING_SELECT_EASING_OPTIONS],
          },
        ],
      },
      {
        title: 'Bottom Slot',
        defaultCollapsed: true,
        controls: [
          {
            id: 'pricingSelect.bottomSlot.background',
            type: 'color-select',
            label: 'Background',
            value: config.pricingSelect.bottomSlot.background,
            options: [...PRICING_SELECT_BACKGROUND_OPTIONS],
          },
          {
            id: 'pricingSelect.bottomSlot.shine',
            type: 'select',
            label: 'Shine',
            value: config.pricingSelect.bottomSlot.shine,
            options: [...SHINE_OPTIONS],
          },
          {
            id: 'pricingSelect.bottomSlot.borderRadius',
            type: 'slider',
            label: 'Border Radius',
            value: config.pricingSelect.bottomSlot.borderRadius,
            min: 0,
            max: 24,
            step: 2,
            formatLabel: (v: number) => `${v}px`,
          },
          {
            id: 'pricingSelect.bottomSlot.inset',
            type: 'slider',
            label: 'Inset',
            value: config.pricingSelect.bottomSlot.inset,
            min: 0,
            max: 12,
            step: 1,
            formatLabel: (v: number) => `${v}px`,
          },
          {
            id: 'pricingSelect.bottomSlot.borderWidth',
            type: 'slider',
            label: 'Border Width',
            value: config.pricingSelect.bottomSlot.borderWidth,
            min: 0,
            max: 3,
            step: 1,
            formatLabel: (v: number) => `${v}px`,
          },
          {
            id: 'pricingSelect.bottomSlot.borderColor',
            type: 'select',
            label: 'Border Color',
            value: config.pricingSelect.bottomSlot.borderColor,
            options: [...PRICING_SELECT_BORDER_COLOR_OPTIONS],
            disabled: config.pricingSelect.bottomSlot.borderWidth === 0,
          },
        ],
      },
      {
        title: 'Interaction',
        defaultCollapsed: true,
        controls: [
          {
            id: 'pricingSelect.triggerHoverBackground',
            type: 'color-select',
            label: 'Trigger Hover',
            value: config.pricingSelect.triggerHoverBackground,
            options: [...PRICING_SELECT_BACKGROUND_OPTIONS],
          },
        ],
      },
    ],
  }
}

function buildAnimationSection(config: PricingPlaygroundConfig): Section {
  return {
    id: 'animation',
    label: 'Animation',
    title: 'Animation',
    groups: [
      {
        controls: [
          {
            id: 'animation.preset',
            type: 'select',
            label: 'Preset',
            value: config.animation.preset,
            options: [...ANIMATION_PRESET_OPTIONS],
          },
          {
            id: 'animation.duration',
            type: 'slider',
            label: 'Duration',
            value: config.animation.duration,
            min: 50,
            max: 500,
            step: 25,
            formatLabel: (v: number) => `${v}ms`,
          },
          {
            id: 'animation.bounce',
            type: 'slider',
            label: 'Bounce',
            value: config.animation.bounce,
            min: 0,
            max: 0.5,
            step: 0.05,
            formatLabel: (v: number) => v.toFixed(2),
          },
        ],
      },
    ],
  }
}

function buildFlowsSection(config: PricingPlaygroundConfig): Section {
  return {
    id: 'flows',
    label: 'Flows',
    title: 'Flows',
    groups: [
      {
        title: 'Flow A',
        controls: [
          {
            id: 'flows.flow-a.headerTitle',
            type: 'text',
            label: 'Title',
            value: config.flows['flow-a'].headerTitle,
          },
          {
            id: 'flows.flow-a.headerSubheader',
            type: 'text',
            label: 'Subheader',
            value: config.flows['flow-a'].headerSubheader,
          },
          {
            id: 'flows.flow-a.asset.showCoinStack',
            type: 'toggle',
            label: 'Show Coin Stack',
            value: config.flows['flow-a'].asset?.showCoinStack ?? true,
            disabled: !config.asset.coinStack.enabled,
          },
          {
            id: 'flows.flow-a.contentA.show',
            type: 'toggle',
            label: 'Show Content A',
            value: config.flows['flow-a'].contentA.show,
          },
          {
            id: 'flows.flow-a.contentA.type',
            type: 'select',
            label: 'Content A Type',
            value: config.flows['flow-a'].contentA.type,
            options: [...CONTENT_TYPE_OPTIONS],
            disabled: !config.flows['flow-a'].contentA.show,
          },
          {
            id: 'flows.flow-a.contentB.show',
            type: 'toggle',
            label: 'Show Content B',
            value: config.flows['flow-a'].contentB.show,
          },
          {
            id: 'flows.flow-a.contentB.type',
            type: 'select',
            label: 'Content B Type',
            value: config.flows['flow-a'].contentB.type,
            options: [...CONTENT_TYPE_OPTIONS],
            disabled: !config.flows['flow-a'].contentB.show,
          },
          {
            id: 'flows.flow-a.buttonLabel',
            type: 'text',
            label: 'Button Label',
            value: config.flows['flow-a'].buttonLabel,
          },
        ],
      },
      {
        title: 'Flow A - Content A Header',
        defaultCollapsed: true,
        controls: [
          {
            id: 'flows.flow-a.contentAHeader.show',
            type: 'toggle',
            label: 'Show Header',
            value: config.flows['flow-a'].contentAHeader?.show ?? false,
            disabled: !config.flows['flow-a'].contentA.show,
          },
          {
            id: 'flows.flow-a.contentAHeader.text',
            type: 'text',
            label: 'Header Text',
            value: config.flows['flow-a'].contentAHeader?.text ?? 'Select your plan',
            disabled: !config.flows['flow-a'].contentA.show || !config.flows['flow-a'].contentAHeader?.show,
          },
          {
            id: 'flows.flow-a.contentAHeader.size',
            type: 'select',
            label: 'Size',
            value: config.flows['flow-a'].contentAHeader?.size ?? 'sm',
            options: [...CONTENT_A_HEADER_SIZE_OPTIONS],
            disabled: !config.flows['flow-a'].contentA.show || !config.flows['flow-a'].contentAHeader?.show,
          },
          {
            id: 'flows.flow-a.contentAHeader.weight',
            type: 'select',
            label: 'Weight',
            value: config.flows['flow-a'].contentAHeader?.weight ?? '500',
            options: [...WEIGHT_OPTIONS],
            disabled: !config.flows['flow-a'].contentA.show || !config.flows['flow-a'].contentAHeader?.show,
          },
          {
            id: 'flows.flow-a.contentAHeader.color',
            type: 'color-select',
            label: 'Color',
            value: config.flows['flow-a'].contentAHeader?.color ?? 'text-secondary',
            options: [...TEXT_COLOR_OPTIONS],
            disabled: !config.flows['flow-a'].contentA.show || !config.flows['flow-a'].contentAHeader?.show,
          },
          {
            id: 'flows.flow-a.contentAHeader.opacity',
            type: 'slider',
            label: 'Opacity',
            value: config.flows['flow-a'].contentAHeader?.opacity ?? 100,
            min: 0,
            max: 100,
            step: 10,
            formatLabel: (v: number) => `${v}%`,
            disabled: !config.flows['flow-a'].contentA.show || !config.flows['flow-a'].contentAHeader?.show,
          },
        ],
      },
      {
        title: 'Flow B',
        controls: [
          {
            id: 'flows.flow-b.headerTitle',
            type: 'text',
            label: 'Title',
            value: config.flows['flow-b'].headerTitle,
          },
          {
            id: 'flows.flow-b.headerSubheader',
            type: 'text',
            label: 'Subheader',
            value: config.flows['flow-b'].headerSubheader,
          },
          {
            id: 'flows.flow-b.asset.showCoinStack',
            type: 'toggle',
            label: 'Show Coin Stack',
            value: config.flows['flow-b'].asset?.showCoinStack ?? true,
            disabled: !config.asset.coinStack.enabled,
          },
          {
            id: 'flows.flow-b.contentA.show',
            type: 'toggle',
            label: 'Show Content A',
            value: config.flows['flow-b'].contentA.show,
          },
          {
            id: 'flows.flow-b.contentA.type',
            type: 'select',
            label: 'Content A Type',
            value: config.flows['flow-b'].contentA.type,
            options: [...CONTENT_TYPE_OPTIONS],
            disabled: !config.flows['flow-b'].contentA.show,
          },
          {
            id: 'flows.flow-b.contentB.show',
            type: 'toggle',
            label: 'Show Content B',
            value: config.flows['flow-b'].contentB.show,
          },
          {
            id: 'flows.flow-b.contentB.type',
            type: 'select',
            label: 'Content B Type',
            value: config.flows['flow-b'].contentB.type,
            options: [...CONTENT_TYPE_OPTIONS],
            disabled: !config.flows['flow-b'].contentB.show,
          },
          {
            id: 'flows.flow-b.buttonLabel',
            type: 'text',
            label: 'Button Label',
            value: config.flows['flow-b'].buttonLabel,
          },
        ],
      },
      {
        title: 'Flow B - Checklist Items',
        description: 'Variables: {planName}, {planNameShort}, {price}, {credits}, {creditsLabel}',
        defaultCollapsed: false,
        controls: [
          {
            id: 'flows.flow-b.checklistItems.0.text',
            type: 'text',
            label: 'Item 1 Text',
            value: config.flows['flow-b'].checklistItems?.[0]?.text ?? '{planName} renews March 20',
            disabled: config.flows['flow-b'].contentB.type !== 'checklist',
          },
          {
            id: 'flows.flow-b.checklistItems.0.date',
            type: 'text',
            label: 'Item 1 Secondary',
            value: config.flows['flow-b'].checklistItems?.[0]?.date ?? '',
            disabled: config.flows['flow-b'].contentB.type !== 'checklist',
          },
          {
            id: 'flows.flow-b.checklistItems.1.text',
            type: 'text',
            label: 'Item 2 Text',
            value: config.flows['flow-b'].checklistItems?.[1]?.text ?? '{credits} credits per month',
            disabled: config.flows['flow-b'].contentB.type !== 'checklist',
          },
          {
            id: 'flows.flow-b.checklistItems.1.date',
            type: 'text',
            label: 'Item 2 Secondary',
            value: config.flows['flow-b'].checklistItems?.[1]?.date ?? '',
            disabled: config.flows['flow-b'].contentB.type !== 'checklist',
          },
          {
            id: 'flows.flow-b.checklistItems.2.text',
            type: 'text',
            label: 'Item 3 Text',
            value: config.flows['flow-b'].checklistItems?.[2]?.text ?? 'Credits roll over',
            disabled: config.flows['flow-b'].contentB.type !== 'checklist',
          },
          {
            id: 'flows.flow-b.checklistItems.2.date',
            type: 'text',
            label: 'Item 3 Secondary',
            value: config.flows['flow-b'].checklistItems?.[2]?.date ?? '',
            disabled: config.flows['flow-b'].contentB.type !== 'checklist',
          },
        ],
      },
      {
        title: 'Flow C',
        controls: [
          {
            id: 'flows.flow-c.headerTitle',
            type: 'text',
            label: 'Title',
            value: config.flows['flow-c'].headerTitle,
          },
          {
            id: 'flows.flow-c.headerSubheader',
            type: 'text',
            label: 'Subheader',
            value: config.flows['flow-c'].headerSubheader,
          },
          {
            id: 'flows.flow-c.asset.showCoinStack',
            type: 'toggle',
            label: 'Show Coin Stack',
            value: config.flows['flow-c'].asset?.showCoinStack ?? true,
            disabled: !config.asset.coinStack.enabled,
          },
          {
            id: 'flows.flow-c.contentA.show',
            type: 'toggle',
            label: 'Show Content A',
            value: config.flows['flow-c'].contentA.show,
          },
          {
            id: 'flows.flow-c.contentA.type',
            type: 'select',
            label: 'Content A Type',
            value: config.flows['flow-c'].contentA.type,
            options: [...CONTENT_TYPE_OPTIONS],
            disabled: !config.flows['flow-c'].contentA.show,
          },
          {
            id: 'flows.flow-c.contentB.show',
            type: 'toggle',
            label: 'Show Content B',
            value: config.flows['flow-c'].contentB.show,
          },
          {
            id: 'flows.flow-c.contentB.type',
            type: 'select',
            label: 'Content B Type',
            value: config.flows['flow-c'].contentB.type,
            options: [...CONTENT_TYPE_OPTIONS],
            disabled: !config.flows['flow-c'].contentB.show,
          },
          {
            id: 'flows.flow-c.buttonLabel',
            type: 'text',
            label: 'Button Label',
            value: config.flows['flow-c'].buttonLabel,
          },
        ],
      },
    ],
  }
}

function buildDemoSection(config: PricingPlaygroundConfig): Section {
  return {
    id: 'demo',
    label: 'Demo',
    title: 'Demo Settings',
    groups: [
      {
        controls: [
          {
            id: 'demo.pageBackground',
            type: 'color-select',
            label: 'Page Background',
            value: config.demo.pageBackground,
            options: [...PAGE_BACKGROUND_OPTIONS],
          },
          {
            id: 'demo.autoOpen',
            type: 'toggle',
            label: 'Auto Open',
            value: config.demo.autoOpen,
          },
          {
            id: 'demo.showOutlines',
            type: 'toggle',
            label: 'Show Outlines',
            value: config.demo.showOutlines,
          },
        ],
      },
    ],
  }
}

function buildBackdropSection(config: PricingPlaygroundConfig): Section {
  return {
    id: 'backdrop',
    label: 'Backdrop',
    title: 'Backdrop',
    groups: [
      {
        controls: [
          {
            id: 'backdrop.opacity',
            type: 'slider',
            label: 'Opacity',
            value: config.backdrop.opacity,
            min: 0,
            max: 100,
            step: 5,
          },
          {
            id: 'backdrop.blur',
            type: 'slider',
            label: 'Blur',
            value: config.backdrop.blur,
            min: 0,
            max: 32,
            step: 2,
          },
          {
            id: 'backdrop.color',
            type: 'color-select',
            label: 'Color',
            value: config.backdrop.color,
            options: [...BACKDROP_COLOR_OPTIONS],
          },
          {
            id: 'backdrop.dismissable',
            type: 'toggle',
            label: 'Dismissable',
            value: config.backdrop.dismissable,
          },
        ],
      },
    ],
  }
}
